<?php
if($values['TELLINE'] != '2'):
  $values['SIP_LOCAL_PHONE_NUM'] = $_POST['sip_phone_number'] ;
  $updatesql.=",SIP_LOCAL_PHONE_NUM='".$values['SIP_LOCAL_PHONE_NUM']."'";
endif; 
if($values['TELLINE'] != '2'):
  $values['SIP_DISPLAY_NAME'] = $_POST['sip_display_name'] ;
  $updatesql.=",SIP_DISPLAY_NAME='".$values['SIP_DISPLAY_NAME']."'";
endif; 
if($values['TELLINE'] != '2'):
  $values['SIP_PROXY'] = $_POST['sip_proxy'] ;
  $updatesql.=",SIP_PROXY='".$values['SIP_PROXY']."'";
endif; 
if($values['TELLINE'] != '2'):
  $values['SIP_REGISTRAR'] = $_POST['sip_registrar'] ;
  $updatesql.=",SIP_REGISTRAR='".$values['SIP_REGISTRAR']."'";
endif; 
if($values['TELLINE'] != '2'):
  $values['SIP_OUTBOUND_PROXY'] = $_POST['sip_outbound_proxy'] ;
  $updatesql.=",SIP_OUTBOUND_PROXY='".$values['SIP_OUTBOUND_PROXY']."'";
endif; 
if($values['TELLINE'] != '2'):
  $values['SIP_CONTACT0_HOME_DOMAIN'] = $_POST['sip_home_domain'] ;
  $updatesql.=",SIP_CONTACT0_HOME_DOMAIN='".$values['SIP_CONTACT0_HOME_DOMAIN']."'";
endif; 
if($values['TELLINE'] != '2'):
  $values['SIP_PHONE_AUTH_ENABLE'] = $_POST['sip_auth']=='on'?'1':'0';
  $updatesql.=",SIP_PHONE_AUTH_ENABLE='".$values['SIP_PHONE_AUTH_ENABLE']."'";
endif; 
  $values['SIP_PHONE_AUTH_ID'] = $_POST['sip_auth_id'] ;
  $updatesql.=",SIP_PHONE_AUTH_ID='".$values['SIP_PHONE_AUTH_ID']."'";
  $values['SIP_PHONE_AUTH_PASSWD'] = $_POST['sip_auth_passwd'] ;
  $updatesql.=",SIP_PHONE_AUTH_PASSWD='".$values['SIP_PHONE_AUTH_PASSWD']."'";
if($values['TELLINE'] != '2'):
  $values['USE_BACKUP_SIP_SVR'] = $_POST['sip_backup_server']=='on'?'1':'0';
  $updatesql.=",USE_BACKUP_SIP_SVR='".$values['USE_BACKUP_SIP_SVR']."'";
endif; 
  $values['SIP_BACKUP_PROXY'] = $_POST['sip_backup_proxy'] ;
  $updatesql.=",SIP_BACKUP_PROXY='".$values['SIP_BACKUP_PROXY']."'";
  $values['SIP_BACKUP_REGISTRAR'] = $_POST['sip_backup_registrar'] ;
  $updatesql.=",SIP_BACKUP_REGISTRAR='".$values['SIP_BACKUP_REGISTRAR']."'";
  $values['SIP_BACKUP_OUTBOUND_PROXY'] = $_POST['sip_backup_outbound_proxy'] ;
  $updatesql.=",SIP_BACKUP_OUTBOUND_PROXY='".$values['SIP_BACKUP_OUTBOUND_PROXY']."'";
  $values['SIP_BACKUP_HOME_DOMAIN'] = $_POST['sip_backup_home_domain'] ;
  $updatesql.=",SIP_BACKUP_HOME_DOMAIN='".$values['SIP_BACKUP_HOME_DOMAIN']."'";
if($values['TELLINE'] != '2'):
  $values['SIP_CONTACT0_FORWARD_TYPE'] = $_POST['sip_fwd_type'] ;
  $updatesql.=",SIP_CONTACT0_FORWARD_TYPE='".$values['SIP_CONTACT0_FORWARD_TYPE']."'";
endif; 
if($values['TELLINE'] != '2'):
  $values['SIP_FORWARD_NUM'] = $_POST['sip_fwd_num'] ;
  $updatesql.=",SIP_FORWARD_NUM='".$values['SIP_FORWARD_NUM']."'";
endif; 
if($values['TELLINE'] != '2'):
  $values['SIP_VOICE_MAIL'] = $_POST['voice_mail'] ;
  $updatesql.=",SIP_VOICE_MAIL='".$values['SIP_VOICE_MAIL']."'";
endif; 
if($values['TELLINE'] == '2'):
endif; 
if($values['TELLINE'] == '2'):
endif; 
  $values['SIP_CONTACT2_DIAL_DIGITS'] = $_POST['sip_profile1_number'] ;
  $updatesql.=",SIP_CONTACT2_DIAL_DIGITS='".$values['SIP_CONTACT2_DIAL_DIGITS']."'";
  $values['SIP_CONTACT2_DISPLAY_NAME'] = $_POST['sip_profile1_display_name'] ;
  $updatesql.=",SIP_CONTACT2_DISPLAY_NAME='".$values['SIP_CONTACT2_DISPLAY_NAME']."'";
  $values['SIP_CONTACT2_PROXY'] = $_POST['sip_profile1_proxy'] ;
  $updatesql.=",SIP_CONTACT2_PROXY='".$values['SIP_CONTACT2_PROXY']."'";
  $values['SIP_CONTACT2_SERVER'] = $_POST['sip_profile1_registrar'] ;
  $updatesql.=",SIP_CONTACT2_SERVER='".$values['SIP_CONTACT2_SERVER']."'";
  $values['SIP_CONTACT2_EXPIRED'] = $_POST['sip_profile1_register_expired'] ;
  $updatesql.=",SIP_CONTACT2_EXPIRED='".$values['SIP_CONTACT2_EXPIRED']."'";
  $values['SIP_CONTACT2_OUTBOUND_PROXY'] = $_POST['sip_profile1_outbound_proxy'] ;
  $updatesql.=",SIP_CONTACT2_OUTBOUND_PROXY='".$values['SIP_CONTACT2_OUTBOUND_PROXY']."'";
  $values['SIP_CONTACT2_HOME_DOMAIN'] = $_POST['sip_profile1_home_domain'] ;
  $updatesql.=",SIP_CONTACT2_HOME_DOMAIN='".$values['SIP_CONTACT2_HOME_DOMAIN']."'";
  $values['SIP_CONTACT2_LOGIN'] = $_POST['sip_profile1_auth_id'] ;
  $updatesql.=",SIP_CONTACT2_LOGIN='".$values['SIP_CONTACT2_LOGIN']."'";
  $values['SIP_CONTACT2_PASSWD'] = $_POST['sip_profile1_auth_passwd'] ;
  $updatesql.=",SIP_CONTACT2_PASSWD='".$values['SIP_CONTACT2_PASSWD']."'";
  $values['SIP_CONTACT2_CALL_WAIT'] = $_POST['sip_profile1_call_wait']=='on'?'1':'0';
  $updatesql.=",SIP_CONTACT2_CALL_WAIT='".$values['SIP_CONTACT2_CALL_WAIT']."'";
  $values['SIP_CONTACT2_FORWARD_TYPE'] = $_POST['sip_profile1_fwd_type'] ;
  $updatesql.=",SIP_CONTACT2_FORWARD_TYPE='".$values['SIP_CONTACT2_FORWARD_TYPE']."'";
  $values['SIP_CONTACT2_FORWARD_NUMBER'] = $_POST['sip_profile1_fwd_num'] ;
  $updatesql.=",SIP_CONTACT2_FORWARD_NUMBER='".$values['SIP_CONTACT2_FORWARD_NUMBER']."'";
  $values['SIP_CONTACT2_VM_NUM'] = $_POST['sip_profile1_vm_num'] ;
  $updatesql.=",SIP_CONTACT2_VM_NUM='".$values['SIP_CONTACT2_VM_NUM']."'";
  $values['P1_HOT_LINE_NUM'] = $_POST['sip_profile1_hot_line_num'] ;
  $updatesql.=",P1_HOT_LINE_NUM='".$values['P1_HOT_LINE_NUM']."'";
  $values['P1_DIAL_PLAN'] = $_POST['sip_profile1_dial_plan'] ;
  $updatesql.=",P1_DIAL_PLAN='".$values['P1_DIAL_PLAN']."'";
  $values['P1_RING_TYPE'] = $_POST['profile1_ring_type'] ;
  $updatesql.=",P1_RING_TYPE='".$values['P1_RING_TYPE']."'";
if($values['AUTO_ANSWER'] != '0'):
  $values['L1_AUTO_ANSWER'] = $_POST['l1_auto_answer_mode'] ;
  $updatesql.=",L1_AUTO_ANSWER='".$values['L1_AUTO_ANSWER']."'";
endif; 
if($values['TELLINE'] == '2'):
endif; 
  $values['SIP_CONTACT3_DIAL_DIGITS'] = $_POST['sip_profile2_number'] ;
  $updatesql.=",SIP_CONTACT3_DIAL_DIGITS='".$values['SIP_CONTACT3_DIAL_DIGITS']."'";
  $values['SIP_CONTACT3_DISPLAY_NAME'] = $_POST['sip_profile2_display_name'] ;
  $updatesql.=",SIP_CONTACT3_DISPLAY_NAME='".$values['SIP_CONTACT3_DISPLAY_NAME']."'";
  $values['SIP_CONTACT3_PROXY'] = $_POST['sip_profile2_proxy'] ;
  $updatesql.=",SIP_CONTACT3_PROXY='".$values['SIP_CONTACT3_PROXY']."'";
  $values['SIP_CONTACT3_SERVER'] = $_POST['sip_profile2_registrar'] ;
  $updatesql.=",SIP_CONTACT3_SERVER='".$values['SIP_CONTACT3_SERVER']."'";
  $values['SIP_CONTACT3_EXPIRED'] = $_POST['sip_profile2_register_expired'] ;
  $updatesql.=",SIP_CONTACT3_EXPIRED='".$values['SIP_CONTACT3_EXPIRED']."'";
  $values['SIP_CONTACT3_OUTBOUND_PROXY'] = $_POST['sip_profile2_outbound_proxy'] ;
  $updatesql.=",SIP_CONTACT3_OUTBOUND_PROXY='".$values['SIP_CONTACT3_OUTBOUND_PROXY']."'";
  $values['SIP_CONTACT3_HOME_DOMAIN'] = $_POST['sip_profile2_home_domain'] ;
  $updatesql.=",SIP_CONTACT3_HOME_DOMAIN='".$values['SIP_CONTACT3_HOME_DOMAIN']."'";
  $values['SIP_CONTACT3_LOGIN'] = $_POST['sip_profile2_auth_id'] ;
  $updatesql.=",SIP_CONTACT3_LOGIN='".$values['SIP_CONTACT3_LOGIN']."'";
  $values['SIP_CONTACT3_PASSWD'] = $_POST['sip_profile2_auth_passwd'] ;
  $updatesql.=",SIP_CONTACT3_PASSWD='".$values['SIP_CONTACT3_PASSWD']."'";
  $values['SIP_CONTACT3_CALL_WAIT'] = $_POST['sip_profile2_call_wait']=='on'?'1':'0';
  $updatesql.=",SIP_CONTACT3_CALL_WAIT='".$values['SIP_CONTACT3_CALL_WAIT']."'";
  $values['SIP_CONTACT3_FORWARD_TYPE'] = $_POST['sip_profile2_fwd_type'] ;
  $updatesql.=",SIP_CONTACT3_FORWARD_TYPE='".$values['SIP_CONTACT3_FORWARD_TYPE']."'";
  $values['SIP_CONTACT3_FORWARD_NUMBER'] = $_POST['sip_profile2_fwd_num'] ;
  $updatesql.=",SIP_CONTACT3_FORWARD_NUMBER='".$values['SIP_CONTACT3_FORWARD_NUMBER']."'";
  $values['SIP_CONTACT3_VM_NUM'] = $_POST['sip_profile2_vm_num'] ;
  $updatesql.=",SIP_CONTACT3_VM_NUM='".$values['SIP_CONTACT3_VM_NUM']."'";
  $values['P2_HOT_LINE_NUM'] = $_POST['sip_profile2_hot_line_num'] ;
  $updatesql.=",P2_HOT_LINE_NUM='".$values['P2_HOT_LINE_NUM']."'";
  $values['P2_DIAL_PLAN'] = $_POST['sip_profile2_dial_plan'] ;
  $updatesql.=",P2_DIAL_PLAN='".$values['P2_DIAL_PLAN']."'";
  $values['P2_RING_TYPE'] = $_POST['profile2_ring_type'] ;
  $updatesql.=",P2_RING_TYPE='".$values['P2_RING_TYPE']."'";
if($values['AUTO_ANSWER'] != '0'):
  $values['L2_AUTO_ANSWER'] = $_POST['l2_auto_answer_mode'] ;
  $updatesql.=",L2_AUTO_ANSWER='".$values['L2_AUTO_ANSWER']."'";
endif; 



  $values['SIP_LOCAL_PORT'] = $_POST['sip_local_port'] ;
  $updatesql.=",SIP_LOCAL_PORT='".$values['SIP_LOCAL_PORT']."'";
  $values['SIP_OPERATION_MODE'] = $_POST['sip_op_mode'] ;
  $updatesql.=",SIP_OPERATION_MODE='".$values['SIP_OPERATION_MODE']."'";
  $values['SIP_PROTOCOL_MODE'] = $_POST['sip_p_mode'] ;
  $updatesql.=",SIP_PROTOCOL_MODE='".$values['SIP_PROTOCOL_MODE']."'";
  $values['SIP_MWI'] = $_POST['sip_mwi']=='on'?'1':'0';
  $updatesql.=",SIP_MWI='".$values['SIP_MWI']."'";
  $values['SIP_DISABLE_CALL_WAIT'] = $_POST['sip_disable_call_wait']=='on'?'0':'1';
  $updatesql.=",SIP_DISABLE_CALL_WAIT='".$values['SIP_DISABLE_CALL_WAIT']."'";
  $values['SIP_NO_ALIVE'] = $_POST['sip_no_alive']=='on'?'0':'1';
  $updatesql.=",SIP_NO_ALIVE='".$values['SIP_NO_ALIVE']."'";
  $values['SIP_P2P_ENABLE'] = $_POST['sip_p2p_enable']=='on'?'1':'0';
  $updatesql.=",SIP_P2P_ENABLE='".$values['SIP_P2P_ENABLE']."'";
  $values['SIP_VIRTUAL_RB_TONE'] = $_POST['sip_virtual_ringback']=='on'?'1':'0';
  $updatesql.=",SIP_VIRTUAL_RB_TONE='".$values['SIP_VIRTUAL_RB_TONE']."'";
  $values['SIP_ROUTE_FIELD_DISABLE'] = $_POST['sip_disable_route_filed']=='on'?'0':'1';
  $updatesql.=",SIP_ROUTE_FIELD_DISABLE='".$values['SIP_ROUTE_FIELD_DISABLE']."'";
  $values['SIP_MUSIC_ON_HOLD'] = $_POST['sip_music_on_hold']=='on'?'1':'0';
  $updatesql.=",SIP_MUSIC_ON_HOLD='".$values['SIP_MUSIC_ON_HOLD']."'";
  $values['SIP_MSG_POUND_AS_POUND'] = $_POST['sip_escape_pkey']=='on'?'0':'1';
  $updatesql.=",SIP_MSG_POUND_AS_POUND='".$values['SIP_MSG_POUND_AS_POUND']."'";
  $values['INBAND_DTMF'] = $_POST['sip_dtmf_type'] ;
  $updatesql.=",INBAND_DTMF='".$values['INBAND_DTMF']."'";
if($values['INBAND_DTMF'] == '0'):
  $values['SIP_OUTBAND_DTMF_TYPE'] = $_POST['sip_outband_dtmf_type'] ;
  $updatesql.=",SIP_OUTBAND_DTMF_TYPE='".$values['SIP_OUTBAND_DTMF_TYPE']."'";
if($values['SIP_OUTBAND_DTMF_TYPE'] == '1'):
  $values['DTMF_PAYLOAD_TYPE'] = $_POST['dtmf_payload'] ;
  $updatesql.=",DTMF_PAYLOAD_TYPE='".$values['DTMF_PAYLOAD_TYPE']."'";
endif; 
endif; 
  $values['SIP_QOS'] = $_POST['sip_qos'] ;
  $updatesql.=",SIP_QOS='".$values['SIP_QOS']."'";
if($values['SIP_QOS'] == 'IPTOS'):
  $values['SIP_TOS'] = $_POST['sip_tos'] ;
  $updatesql.=",SIP_TOS='".$values['SIP_TOS']."'";
endif; 
if($values['SIP_QOS'] == 'DIFFSERV'):
  $values['SIP_DIFFSERV'] = $_POST['sip_diffserv_class'] ;
  $updatesql.=",SIP_DIFFSERV='".$values['SIP_DIFFSERV']."'";
endif; 
if($values['SIP_CRYPT'] != 'DISABLE'):
  $values['SIP_CRYPT'] = $_POST['sip_signaling_crypt'] ;
  $updatesql.=",SIP_CRYPT='".$values['SIP_CRYPT']."'";
endif; 
if($values['SIP_CRYPT'] == 'RC4'):
  $values['SIP_RC4_KEY'] = $_POST['sip_rc4_key'] ;
  $updatesql.=",SIP_RC4_KEY='".$values['SIP_RC4_KEY']."'";
endif; 
if($values['SIP_CRYPT'] == 'ECM'):
  $values['ECM_CRYPT_KEY'] = $_POST['sip_ecm_crypt_key'] ;
  $updatesql.=",ECM_CRYPT_KEY='".$values['ECM_CRYPT_KEY']."'";
endif; 
if($values['SIP_CRYPT'] == 'ET263'):
  $values['SIP_ET263_CRYPT_TYPE'] = $_POST['sip_et263_crypt_type'] ;
  $updatesql.=",SIP_ET263_CRYPT_TYPE='".$values['SIP_ET263_CRYPT_TYPE']."'";
  $values['SIP_ET263_CRYPT_DEP'] = $_POST['sip_et263_crypt_dep'] ;
  $updatesql.=",SIP_ET263_CRYPT_DEP='".$values['SIP_ET263_CRYPT_DEP']."'";
endif; 
  $values['SIP_NAT_TRAVERSAL'] = $_POST['sip_nat_traversal'] ;
  $updatesql.=",SIP_NAT_TRAVERSAL='".$values['SIP_NAT_TRAVERSAL']."'";
if($values['SIP_NAT_TRAVERSAL'] == 'STUN'):
  $values['SIP_STUN_SERVER'] = $_POST['sip_stun_server'] ;
  $updatesql.=",SIP_STUN_SERVER='".$values['SIP_STUN_SERVER']."'";
endif; 
if($values['SIP_NAT_TRAVERSAL'] == 'RELAY'):
  $values['SIP_RELAY_SERVER'] = $_POST['sip_relay_server'] ;
  $updatesql.=",SIP_RELAY_SERVER='".$values['SIP_RELAY_SERVER']."'";
  $values['SIP_RELAY_PORT'] = $_POST['sip_relay_port'] ;
  $updatesql.=",SIP_RELAY_PORT='".$values['SIP_RELAY_PORT']."'";
  $values['SIP_RELAY_USER'] = $_POST['sip_relay_user'] ;
  $updatesql.=",SIP_RELAY_USER='".$values['SIP_RELAY_USER']."'";
  $values['SIP_RELAY_PASSWD'] = $_POST['sip_relay_passwd'] ;
  $updatesql.=",SIP_RELAY_PASSWD='".$values['SIP_RELAY_PASSWD']."'";
  $values['SIP_RELAY_ENCRYPT'] = $_POST['sip_relay_encrypt']=='on'?'1':'0';
  $updatesql.=",SIP_RELAY_ENCRYPT='".$values['SIP_RELAY_ENCRYPT']."'";
  $values['SIP_RELAY_SERVER1'] = $_POST['sip_relay_server1'] ;
  $updatesql.=",SIP_RELAY_SERVER1='".$values['SIP_RELAY_SERVER1']."'";
  $values['SIP_RELAY_SERVER2'] = $_POST['sip_relay_server2'] ;
  $updatesql.=",SIP_RELAY_SERVER2='".$values['SIP_RELAY_SERVER2']."'";
  $values['SIP_RELAY_SERVER3'] = $_POST['sip_relay_server3'] ;
  $updatesql.=",SIP_RELAY_SERVER3='".$values['SIP_RELAY_SERVER3']."'";
  $values['SIP_RELAY_SERVER4'] = $_POST['sip_relay_server4'] ;
  $updatesql.=",SIP_RELAY_SERVER4='".$values['SIP_RELAY_SERVER4']."'";
endif; 



  $values['RTP_PORT'] = $_POST['rtp_port_lower']."-".$_POST['rtp_port_upper'] ;
  $updatesql.=",RTP_PORT='".$values['RTP_PORT']."'";
  $values['PACKETIZE_PERIOD'] = $_POST['rtp_pkt_len'] ;
  $updatesql.=",PACKETIZE_PERIOD='".$values['PACKETIZE_PERIOD']."'";
  $values['VPDSP_JB_MODE'] = $_POST['jb_mode'] ;
  $updatesql.=",VPDSP_JB_MODE='".$values['VPDSP_JB_MODE']."'";
  $values['VPDSP_ADPT_MIN_JITTER'] = $_POST['adpt_min_jitter'] ;
  $updatesql.=",VPDSP_ADPT_MIN_JITTER='".$values['VPDSP_ADPT_MIN_JITTER']."'";
  $values['VPDSP_ADPT_MAX_JITTER'] = $_POST['adpt_max_jitter'] ;
  $updatesql.=",VPDSP_ADPT_MAX_JITTER='".$values['VPDSP_ADPT_MAX_JITTER']."'";
  $values['VPDSP_SEQ_MIN_JITTER'] = $_POST['seq_min_jitter'] ;
  $updatesql.=",VPDSP_SEQ_MIN_JITTER='".$values['VPDSP_SEQ_MIN_JITTER']."'";
  $values['VPDSP_SEQ_MAX_JITTER'] = $_POST['seq_max_jitter'] ;
  $updatesql.=",VPDSP_SEQ_MAX_JITTER='".$values['VPDSP_SEQ_MAX_JITTER']."'";
  $values['VPDSP_MIN_JITTER'] = $_POST['jitter_buffer'] ;
  $updatesql.=",VPDSP_MIN_JITTER='".$values['VPDSP_MIN_JITTER']."'";
  $values['RTP_QOS'] = $_POST['rtp_qos'] ;
  $updatesql.=",RTP_QOS='".$values['RTP_QOS']."'";
  $values['RTP_TOS'] = $_POST['rtp_tos'] ;
  $updatesql.=",RTP_TOS='".$values['RTP_TOS']."'";
  $values['RTP_DIFFSERV'] = $_POST['rtp_diffserv_class'] ;
  $updatesql.=",RTP_DIFFSERV='".$values['RTP_DIFFSERV']."'";
if($values['MG_CRYPT'] != 'DISABLE'):
  $values['MG_CRYPT'] = $_POST['rtp_crypt'] ;
  $updatesql.=",MG_CRYPT='".$values['MG_CRYPT']."'";
endif; 
  $values['MG_RC4_KEY'] = $_POST['rtp_rc4_key'] ;
  $updatesql.=",MG_RC4_KEY='".$values['MG_RC4_KEY']."'";
if($values['ET263_CRYPT'] == '1'):
endif; 
  $values['MG_ET263_CRYPT_TYPE'] = $_POST['rtp_et263_crypt_type'] ;
  $updatesql.=",MG_ET263_CRYPT_TYPE='".$values['MG_ET263_CRYPT_TYPE']."'";
  $values['MG_ET263_CRYPT_DEP'] = $_POST['rtp_et263_crypt_dep'] ;
  $updatesql.=",MG_ET263_CRYPT_DEP='".$values['MG_ET263_CRYPT_DEP']."'";
  $values['SYMMETRIC_RTP'] = $_POST['symmetric_rtp']=='on'?'1':'0';
  $updatesql.=",SYMMETRIC_RTP='".$values['SYMMETRIC_RTP']."'";
  $values['MG_NAT_TRAVERSAL'] = $_POST['rtp_nat_traversal'] ;
  $updatesql.=",MG_NAT_TRAVERSAL='".$values['MG_NAT_TRAVERSAL']."'";
  $values['MG_STUN_SERVER'] = $_POST['rtp_stun_server'] ;
  $updatesql.=",MG_STUN_SERVER='".$values['MG_STUN_SERVER']."'";
  $values['MG_PORTFWD_TYPE'] = $_POST['rtp_portfwd_type'] ;
  $updatesql.=",MG_PORTFWD_TYPE='".$values['MG_PORTFWD_TYPE']."'";
  $values['MG_PORTFWD_GW'] = $_POST['rtp_portfwd_gw'] ;
  $updatesql.=",MG_PORTFWD_GW='".$values['MG_PORTFWD_GW']."'";
  $values['MG_RELAY_SERVER'] = $_POST['rtp_relay_server'] ;
  $updatesql.=",MG_RELAY_SERVER='".$values['MG_RELAY_SERVER']."'";
  $values['MG_RELAY_PORT'] = $_POST['rtp_relay_port'] ;
  $updatesql.=",MG_RELAY_PORT='".$values['MG_RELAY_PORT']."'";
  $values['MG_RELAY_USER'] = $_POST['rtp_relay_user'] ;
  $updatesql.=",MG_RELAY_USER='".$values['MG_RELAY_USER']."'";
  $values['MG_RELAY_PASSWD'] = $_POST['rtp_relay_passwd'] ;
  $updatesql.=",MG_RELAY_PASSWD='".$values['MG_RELAY_PASSWD']."'";
  $values['MG_RELAY_ENCRYPT'] = $_POST['rtp_relay_encrypt']=='on'?'1':'0';
  $updatesql.=",MG_RELAY_ENCRYPT='".$values['MG_RELAY_ENCRYPT']."'";
  $values['MG_RELAY_MODE'] = $_POST['rtp_relay_mode'] ;
  $updatesql.=",MG_RELAY_MODE='".$values['MG_RELAY_MODE']."'";
  $values['MG_RELAY_SERVER1'] = $_POST['rtp_relay_server1'] ;
  $updatesql.=",MG_RELAY_SERVER1='".$values['MG_RELAY_SERVER1']."'";
  $values['MG_RELAY_SERVER2'] = $_POST['rtp_relay_server2'] ;
  $updatesql.=",MG_RELAY_SERVER2='".$values['MG_RELAY_SERVER2']."'";
  $values['MG_RELAY_SERVER3'] = $_POST['rtp_relay_server3'] ;
  $updatesql.=",MG_RELAY_SERVER3='".$values['MG_RELAY_SERVER3']."'";
  $values['MG_RELAY_SERVER4'] = $_POST['rtp_relay_server4'] ;
  $updatesql.=",MG_RELAY_SERVER4='".$values['MG_RELAY_SERVER4']."'";
if($values['SIDE_TONE'] == '1'):
  $values['VPDSP_SIDE_TONE'] = $_POST['side_tone_level'] ;
  $updatesql.=",VPDSP_SIDE_TONE='".$values['VPDSP_SIDE_TONE']."'";
endif; 


  $values['L1_AUTO_ANSWER_NUM_1'] = $_POST['l1_auto_answer_num1'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_1='".$values['L1_AUTO_ANSWER_NUM_1']."'";
  $values['L1_AUTO_ANSWER_NUM_2'] = $_POST['l1_auto_answer_num2'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_2='".$values['L1_AUTO_ANSWER_NUM_2']."'";
  $values['L1_AUTO_ANSWER_NUM_3'] = $_POST['l1_auto_answer_num3'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_3='".$values['L1_AUTO_ANSWER_NUM_3']."'";
  $values['L1_AUTO_ANSWER_NUM_4'] = $_POST['l1_auto_answer_num4'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_4='".$values['L1_AUTO_ANSWER_NUM_4']."'";
  $values['L1_AUTO_ANSWER_NUM_5'] = $_POST['l1_auto_answer_num5'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_5='".$values['L1_AUTO_ANSWER_NUM_5']."'";
  $values['L1_AUTO_ANSWER_NUM_6'] = $_POST['l1_auto_answer_num6'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_6='".$values['L1_AUTO_ANSWER_NUM_6']."'";
  $values['L1_AUTO_ANSWER_NUM_7'] = $_POST['l1_auto_answer_num7'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_7='".$values['L1_AUTO_ANSWER_NUM_7']."'";
  $values['L1_AUTO_ANSWER_NUM_8'] = $_POST['l1_auto_answer_num8'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_8='".$values['L1_AUTO_ANSWER_NUM_8']."'";
  $values['L1_AUTO_ANSWER_NUM_9'] = $_POST['l1_auto_answer_num9'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_9='".$values['L1_AUTO_ANSWER_NUM_9']."'";
  $values['L1_AUTO_ANSWER_NUM_10'] = $_POST['l1_auto_answer_num10'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_10='".$values['L1_AUTO_ANSWER_NUM_10']."'";
  $values['L1_AUTO_ANSWER_NUM_11'] = $_POST['l1_auto_answer_num11'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_11='".$values['L1_AUTO_ANSWER_NUM_11']."'";
  $values['L1_AUTO_ANSWER_NUM_12'] = $_POST['l1_auto_answer_num12'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_12='".$values['L1_AUTO_ANSWER_NUM_12']."'";
  $values['L1_AUTO_ANSWER_NUM_13'] = $_POST['l1_auto_answer_num13'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_13='".$values['L1_AUTO_ANSWER_NUM_13']."'";
  $values['L1_AUTO_ANSWER_NUM_14'] = $_POST['l1_auto_answer_num14'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_14='".$values['L1_AUTO_ANSWER_NUM_14']."'";
  $values['L1_AUTO_ANSWER_NUM_15'] = $_POST['l1_auto_answer_num15'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_15='".$values['L1_AUTO_ANSWER_NUM_15']."'";
  $values['L1_AUTO_ANSWER_NUM_16'] = $_POST['l1_auto_answer_num16'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_16='".$values['L1_AUTO_ANSWER_NUM_16']."'";
  $values['L1_AUTO_ANSWER_NUM_17'] = $_POST['l1_auto_answer_num17'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_17='".$values['L1_AUTO_ANSWER_NUM_17']."'";
  $values['L1_AUTO_ANSWER_NUM_18'] = $_POST['l1_auto_answer_num18'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_18='".$values['L1_AUTO_ANSWER_NUM_18']."'";
  $values['L1_AUTO_ANSWER_NUM_19'] = $_POST['l1_auto_answer_num19'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_19='".$values['L1_AUTO_ANSWER_NUM_19']."'";
  $values['L1_AUTO_ANSWER_NUM_20'] = $_POST['l1_auto_answer_num20'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_20='".$values['L1_AUTO_ANSWER_NUM_20']."'";

  $values['L2_AUTO_ANSWER_NUM_1'] = $_POST['l2_auto_answer_num1'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_1='".$values['L2_AUTO_ANSWER_NUM_1']."'";
  $values['L2_AUTO_ANSWER_NUM_2'] = $_POST['l2_auto_answer_num2'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_2='".$values['L2_AUTO_ANSWER_NUM_2']."'";
  $values['L2_AUTO_ANSWER_NUM_3'] = $_POST['l2_auto_answer_num3'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_3='".$values['L2_AUTO_ANSWER_NUM_3']."'";
  $values['L2_AUTO_ANSWER_NUM_4'] = $_POST['l2_auto_answer_num4'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_4='".$values['L2_AUTO_ANSWER_NUM_4']."'";
  $values['L2_AUTO_ANSWER_NUM_5'] = $_POST['l2_auto_answer_num5'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_5='".$values['L2_AUTO_ANSWER_NUM_5']."'";
  $values['L2_AUTO_ANSWER_NUM_6'] = $_POST['l2_auto_answer_num6'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_6='".$values['L2_AUTO_ANSWER_NUM_6']."'";
  $values['L2_AUTO_ANSWER_NUM_7'] = $_POST['l2_auto_answer_num7'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_7='".$values['L2_AUTO_ANSWER_NUM_7']."'";
  $values['L2_AUTO_ANSWER_NUM_8'] = $_POST['l2_auto_answer_num8'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_8='".$values['L2_AUTO_ANSWER_NUM_8']."'";
  $values['L2_AUTO_ANSWER_NUM_9'] = $_POST['l2_auto_answer_num9'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_9='".$values['L2_AUTO_ANSWER_NUM_9']."'";
  $values['L2_AUTO_ANSWER_NUM_10'] = $_POST['l2_auto_answer_num10'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_10='".$values['L2_AUTO_ANSWER_NUM_10']."'";
  $values['L2_AUTO_ANSWER_NUM_11'] = $_POST['l2_auto_answer_num11'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_11='".$values['L2_AUTO_ANSWER_NUM_11']."'";
  $values['L2_AUTO_ANSWER_NUM_12'] = $_POST['l2_auto_answer_num12'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_12='".$values['L2_AUTO_ANSWER_NUM_12']."'";
  $values['L2_AUTO_ANSWER_NUM_13'] = $_POST['l2_auto_answer_num13'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_13='".$values['L2_AUTO_ANSWER_NUM_13']."'";
  $values['L2_AUTO_ANSWER_NUM_14'] = $_POST['l2_auto_answer_num14'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_14='".$values['L2_AUTO_ANSWER_NUM_14']."'";
  $values['L2_AUTO_ANSWER_NUM_15'] = $_POST['l2_auto_answer_num15'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_15='".$values['L2_AUTO_ANSWER_NUM_15']."'";
  $values['L2_AUTO_ANSWER_NUM_16'] = $_POST['l2_auto_answer_num16'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_16='".$values['L2_AUTO_ANSWER_NUM_16']."'";
  $values['L2_AUTO_ANSWER_NUM_17'] = $_POST['l2_auto_answer_num17'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_17='".$values['L2_AUTO_ANSWER_NUM_17']."'";
  $values['L2_AUTO_ANSWER_NUM_18'] = $_POST['l2_auto_answer_num18'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_18='".$values['L2_AUTO_ANSWER_NUM_18']."'";
  $values['L2_AUTO_ANSWER_NUM_19'] = $_POST['l2_auto_answer_num19'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_19='".$values['L2_AUTO_ANSWER_NUM_19']."'";
  $values['L2_AUTO_ANSWER_NUM_20'] = $_POST['l2_auto_answer_num20'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_20='".$values['L2_AUTO_ANSWER_NUM_20']."'";

  $values['P2_PREFER_CODEC1'] = $_POST['p2_prefer_codec1'] ;
  $updatesql.=",P2_PREFER_CODEC1='".$values['P2_PREFER_CODEC1']."'";
  $values['P2_CODEC1_DISABLE'] = $_POST['p2_codec1_enabled']=='on'?'0':'1';
  $updatesql.=",P2_CODEC1_DISABLE='".$values['P2_CODEC1_DISABLE']."'";
  $values['P2_PREFER_CODEC2'] = $_POST['p2_prefer_codec2'] ;
  $updatesql.=",P2_PREFER_CODEC2='".$values['P2_PREFER_CODEC2']."'";
  $values['P2_CODEC2_DISABLE'] = $_POST['p2_codec2_enabled']=='on'?'0':'1';
  $updatesql.=",P2_CODEC2_DISABLE='".$values['P2_CODEC2_DISABLE']."'";
  $values['P2_PREFER_CODEC3'] = $_POST['p2_prefer_codec3'] ;
  $updatesql.=",P2_PREFER_CODEC3='".$values['P2_PREFER_CODEC3']."'";
  $values['P2_CODEC3_DISABLE'] = $_POST['p2_codec3_enabled']=='on'?'0':'1';
  $updatesql.=",P2_CODEC3_DISABLE='".$values['P2_CODEC3_DISABLE']."'";
  $values['P2_PREFER_CODEC4'] = $_POST['p2_prefer_codec4'] ;
  $updatesql.=",P2_PREFER_CODEC4='".$values['P2_PREFER_CODEC4']."'";
  $values['P2_CODEC4_DISABLE'] = $_POST['p2_codec4_enabled']=='on'?'0':'1';
  $updatesql.=",P2_CODEC4_DISABLE='".$values['P2_CODEC4_DISABLE']."'";
  $values['P2_PREFER_CODEC5'] = $_POST['p2_prefer_codec5'] ;
  $updatesql.=",P2_PREFER_CODEC5='".$values['P2_PREFER_CODEC5']."'";
  $values['P2_CODEC5_DISABLE'] = $_POST['p2_codec5_enabled']=='on'?'0':'1';
  $updatesql.=",P2_CODEC5_DISABLE='".$values['P2_CODEC5_DISABLE']."'";
  $values['P2_PREFER_CODEC6'] = $_POST['p2_prefer_codec6'] ;
  $updatesql.=",P2_PREFER_CODEC6='".$values['P2_PREFER_CODEC6']."'";
  $values['P2_CODEC6_DISABLE'] = $_POST['p2_codec6_enabled']=='on'?'0':'1';
  $updatesql.=",P2_CODEC6_DISABLE='".$values['P2_CODEC6_DISABLE']."'";
  $values['P2_PREFER_CODEC7'] = $_POST['p2_prefer_codec7'] ;
  $updatesql.=",P2_PREFER_CODEC7='".$values['P2_PREFER_CODEC7']."'";
  $values['P2_CODEC7_DISABLE'] = $_POST['p2_codec7_enabled']=='on'?'0':'1';
  $updatesql.=",P2_CODEC7_DISABLE='".$values['P2_CODEC7_DISABLE']."'";

  $values['P3_PREFER_CODEC1'] = $_POST['p3_prefer_codec1'] ;
  $updatesql.=",P3_PREFER_CODEC1='".$values['P3_PREFER_CODEC1']."'";
  $values['P3_CODEC1_DISABLE'] = $_POST['p3_codec1_enabled']=='on'?'0':'1';
  $updatesql.=",P3_CODEC1_DISABLE='".$values['P3_CODEC1_DISABLE']."'";
  $values['P3_PREFER_CODEC2'] = $_POST['p3_prefer_codec2'] ;
  $updatesql.=",P3_PREFER_CODEC2='".$values['P3_PREFER_CODEC2']."'";
  $values['P3_CODEC2_DISABLE'] = $_POST['p3_codec2_enabled']=='on'?'0':'1';
  $updatesql.=",P3_CODEC2_DISABLE='".$values['P3_CODEC2_DISABLE']."'";
  $values['P3_PREFER_CODEC3'] = $_POST['p3_prefer_codec3'] ;
  $updatesql.=",P3_PREFER_CODEC3='".$values['P3_PREFER_CODEC3']."'";
  $values['P3_CODEC3_DISABLE'] = $_POST['p3_codec3_enabled']=='on'?'0':'1';
  $updatesql.=",P3_CODEC3_DISABLE='".$values['P3_CODEC3_DISABLE']."'";
  $values['P3_PREFER_CODEC4'] = $_POST['p3_prefer_codec4'] ;
  $updatesql.=",P3_PREFER_CODEC4='".$values['P3_PREFER_CODEC4']."'";
  $values['P3_CODEC4_DISABLE'] = $_POST['p3_codec4_enabled']=='on'?'0':'1';
  $updatesql.=",P3_CODEC4_DISABLE='".$values['P3_CODEC4_DISABLE']."'";
  $values['P3_PREFER_CODEC5'] = $_POST['p3_prefer_codec5'] ;
  $updatesql.=",P3_PREFER_CODEC5='".$values['P3_PREFER_CODEC5']."'";
  $values['P3_CODEC5_DISABLE'] = $_POST['p3_codec5_enabled']=='on'?'0':'1';
  $updatesql.=",P3_CODEC5_DISABLE='".$values['P3_CODEC5_DISABLE']."'";
  $values['P3_PREFER_CODEC6'] = $_POST['p3_prefer_codec6'] ;
  $updatesql.=",P3_PREFER_CODEC6='".$values['P3_PREFER_CODEC6']."'";
  $values['P3_CODEC6_DISABLE'] = $_POST['p3_codec6_enabled']=='on'?'0':'1';
  $updatesql.=",P3_CODEC6_DISABLE='".$values['P3_CODEC6_DISABLE']."'";
  $values['P3_PREFER_CODEC7'] = $_POST['p3_prefer_codec7'] ;
  $updatesql.=",P3_PREFER_CODEC7='".$values['P3_PREFER_CODEC7']."'";
  $values['P3_CODEC7_DISABLE'] = $_POST['p3_codec7_enabled']=='on'?'0':'1';
  $updatesql.=",P3_CODEC7_DISABLE='".$values['P3_CODEC7_DISABLE']."'";



  $values['SIP_KEEPALIVE_INTERVAL'] = $_POST['sip_keepalive_interval'] ;
  $updatesql.=",SIP_KEEPALIVE_INTERVAL='".$values['SIP_KEEPALIVE_INTERVAL']."'";
  $values['SIP_FAIL_RETRY_INTERVAL'] = $_POST['sip_fail_retry_interval'] ;                                        
  $updatesql.=",SIP_FAIL_RETRY_INTERVAL='".$values['SIP_FAIL_RETRY_INTERVAL']."'";
  
if($values['TELLINE'] != '2'):
  $values['SIP_REGISTER_EXPIRY'] = $_POST['sip_register_expiry'] ;
  $updatesql.=",SIP_REGISTER_EXPIRY='".$values['SIP_REGISTER_EXPIRY']."'";
endif; 
if($values['TELLINE'] != '2'):
  $values['SIP_SUBSCRIBE_EXPIRY'] = $_POST['sip_subscribe_expiry'] ;
  $updatesql.=",SIP_SUBSCRIBE_EXPIRY='".$values['SIP_SUBSCRIBE_EXPIRY']."'";
endif; 
  $values['UNANSWER_FW_EXP'] = $_POST['unanswer_fw_exp'] ;
  $updatesql.=",UNANSWER_FW_EXP='".$values['UNANSWER_FW_EXP']."'";
  $values['UNANSWER_EXP'] = $_POST['unanswer_exp'] ;
  $updatesql.=",UNANSWER_EXP='".$values['UNANSWER_EXP']."'";
  $values['NON_INVITE_TS_EXP'] = $_POST['non_invite_exp'] ;
  $updatesql.=",NON_INVITE_TS_EXP='".$values['NON_INVITE_TS_EXP']."'";
  $values['INVITE_TS_EXP'] = $_POST['invite_exp'] ;                                                               
  $updatesql.=",INVITE_TS_EXP='".$values['INVITE_TS_EXP']."'";                                                    
  $values['RETRANSMIT_T1'] = $_POST['retrans_t1'] ;                                                               
  $updatesql.=",RETRANSMIT_T1='".$values['RETRANSMIT_T1']."'";                                                    
  $values['RETRANSMIT_T2'] = $_POST['retrans_t2'] ;                                                               
  $updatesql.=",RETRANSMIT_T2='".$values['RETRANSMIT_T2']."'";                                                    
                                                                  

/*autocfg srv*/
  $values['AUTOCFG'] = $_POST['auto_config']=='on'?'1':'0';
  $updatesql.=",AUTOCFG='".$values['AUTOCFG']."'";
if($values['AUTOCFG'] == 1):
  $values['AUTOCFG_SERVER'] = $_POST['auto_config_server'] ;
  $updatesql.=",AUTOCFG_SERVER='".$values['AUTOCFG_SERVER']."'";
  $values['AUTOCFG_REFRESH'] = $_POST['auto_config_refresh'] ;
  $updatesql.=",AUTOCFG_REFRESH='".$values['AUTOCFG_REFRESH']."'";
endif;   
  $values['RADMIN_ENABLE'] = $_POST['remote_enable']=='on'?'1':'0';
  $updatesql.=",RADMIN_ENABLE='".$values['RADMIN_ENABLE']."'";
  $values['RADMIN_SERVER'] = $_POST['remote_server'] ;
  $updatesql.=",RADMIN_SERVER='".$values['RADMIN_SERVER']."'";
  $values['RADMIN_PORT'] = $_POST['remote_server_port'] ;
  $updatesql.=",RADMIN_PORT='".$values['RADMIN_PORT']."'";
  $values['RADMIN_ID'] = $_POST['remote_server_id'] ;
  $updatesql.=",RADMIN_ID='".$values['RADMIN_ID']."'";
  $values['RADMIN_KEY'] = $_POST['remote_server_key'] ;
  $updatesql.=",RADMIN_KEY='".$values['RADMIN_KEY']."'";


  $insertsql.=",TELLINE";                                                                             
  $insertsql2.="','2";

  $insertsql.=",SIP_LOCAL_PHONE_NUM";
  $insertsql2.="','".$values['SIP_LOCAL_PHONE_NUM'];
  $insertsql.=",SIP_DISPLAY_NAME";
  $insertsql2.="','".$values['SIP_DISPLAY_NAME'];
  $insertsql.=",SIP_PROXY";
  $insertsql2.="','".$values['SIP_PROXY'];
  $insertsql.=",SIP_REGISTRAR";
  $insertsql2.="','".$values['SIP_REGISTRAR'];
  $insertsql.=",SIP_OUTBOUND_PROXY";
  $insertsql2.="','".$values['SIP_OUTBOUND_PROXY'];
  $insertsql.=",SIP_CONTACT0_HOME_DOMAIN";
  $insertsql2.="','".$values['SIP_CONTACT0_HOME_DOMAIN'];
  $insertsql.=",SIP_PHONE_AUTH_ENABLE";
  $insertsql2.="','".$values['SIP_PHONE_AUTH_ENABLE'];
  $insertsql.=",SIP_PHONE_AUTH_ID";
  $insertsql2.="','".$values['SIP_PHONE_AUTH_ID'];
  $insertsql.=",SIP_PHONE_AUTH_PASSWD";
  $insertsql2.="','".$values['SIP_PHONE_AUTH_PASSWD'];
  $insertsql.=",USE_BACKUP_SIP_SVR";
  $insertsql2.="','".$values['USE_BACKUP_SIP_SVR'];
  $insertsql.=",SIP_BACKUP_PROXY";
  $insertsql2.="','".$values['SIP_BACKUP_PROXY'];
  $insertsql.=",SIP_BACKUP_REGISTRAR";
  $insertsql2.="','".$values['SIP_BACKUP_REGISTRAR'];
  $insertsql.=",SIP_BACKUP_OUTBOUND_PROXY";
  $insertsql2.="','".$values['SIP_BACKUP_OUTBOUND_PROXY'];
  $insertsql.=",SIP_BACKUP_HOME_DOMAIN";
  $insertsql2.="','".$values['SIP_BACKUP_HOME_DOMAIN'];
  $insertsql.=",SIP_CONTACT0_FORWARD_TYPE";
  $insertsql2.="','".$values['SIP_CONTACT0_FORWARD_TYPE'];
  $insertsql.=",SIP_FORWARD_NUM";
  $insertsql2.="','".$values['SIP_FORWARD_NUM'];
  $insertsql.=",SIP_VOICE_MAIL";
  $insertsql2.="','".$values['SIP_VOICE_MAIL'];
  $insertsql.=",SIP_CONTACT2_DIAL_DIGITS";
  $insertsql2.="','".$values['SIP_CONTACT2_DIAL_DIGITS'];
  $insertsql.=",SIP_CONTACT2_DISPLAY_NAME";
  $insertsql2.="','".$values['SIP_CONTACT2_DISPLAY_NAME'];
  $insertsql.=",SIP_CONTACT2_PROXY";
  $insertsql2.="','".$values['SIP_CONTACT2_PROXY'];
  $insertsql.=",SIP_CONTACT2_SERVER";
  $insertsql2.="','".$values['SIP_CONTACT2_SERVER'];
  $insertsql.=",SIP_CONTACT2_EXPIRED";
  $insertsql2.="','".$values['SIP_CONTACT2_EXPIRED'];
  $insertsql.=",SIP_CONTACT2_OUTBOUND_PROXY";
  $insertsql2.="','".$values['SIP_CONTACT2_OUTBOUND_PROXY'];
  $insertsql.=",SIP_CONTACT2_HOME_DOMAIN";
  $insertsql2.="','".$values['SIP_CONTACT2_HOME_DOMAIN'];
  $insertsql.=",SIP_CONTACT2_LOGIN";
  $insertsql2.="','".$values['SIP_CONTACT2_LOGIN'];
  $insertsql.=",SIP_CONTACT2_PASSWD";
  $insertsql2.="','".$values['SIP_CONTACT2_PASSWD'];
  $insertsql.=",SIP_CONTACT2_CALL_WAIT";
  $insertsql2.="','".$values['SIP_CONTACT2_CALL_WAIT'];
  $insertsql.=",SIP_CONTACT2_FORWARD_TYPE";
  $insertsql2.="','".$values['SIP_CONTACT2_FORWARD_TYPE'];
  $insertsql.=",SIP_CONTACT2_FORWARD_NUMBER";
  $insertsql2.="','".$values['SIP_CONTACT2_FORWARD_NUMBER'];
  $insertsql.=",SIP_CONTACT2_VM_NUM";
  $insertsql2.="','".$values['SIP_CONTACT2_VM_NUM'];
  $insertsql.=",P1_HOT_LINE_NUM";
  $insertsql2.="','".$values['P1_HOT_LINE_NUM'];
  $insertsql.=",P1_DIAL_PLAN";
  $insertsql2.="','".$values['P1_DIAL_PLAN'];
  $insertsql.=",P1_RING_TYPE";
  $insertsql2.="','".$values['P1_RING_TYPE'];
  $insertsql.=",L1_AUTO_ANSWER";
  $insertsql2.="','".$values['L1_AUTO_ANSWER'];
  $insertsql.=",SIP_CONTACT3_DIAL_DIGITS";
  $insertsql2.="','".$values['SIP_CONTACT3_DIAL_DIGITS'];
  $insertsql.=",SIP_CONTACT3_DISPLAY_NAME";
  $insertsql2.="','".$values['SIP_CONTACT3_DISPLAY_NAME'];
  $insertsql.=",SIP_CONTACT3_PROXY";
  $insertsql2.="','".$values['SIP_CONTACT3_PROXY'];
  $insertsql.=",SIP_CONTACT3_SERVER";
  $insertsql2.="','".$values['SIP_CONTACT3_SERVER'];
  $insertsql.=",SIP_CONTACT3_EXPIRED";
  $insertsql2.="','".$values['SIP_CONTACT3_EXPIRED'];
  $insertsql.=",SIP_CONTACT3_OUTBOUND_PROXY";
  $insertsql2.="','".$values['SIP_CONTACT3_OUTBOUND_PROXY'];
  $insertsql.=",SIP_CONTACT3_HOME_DOMAIN";
  $insertsql2.="','".$values['SIP_CONTACT3_HOME_DOMAIN'];
  $insertsql.=",SIP_CONTACT3_LOGIN";
  $insertsql2.="','".$values['SIP_CONTACT3_LOGIN'];
  $insertsql.=",SIP_CONTACT3_PASSWD";
  $insertsql2.="','".$values['SIP_CONTACT3_PASSWD'];
  $insertsql.=",SIP_CONTACT3_CALL_WAIT";
  $insertsql2.="','".$values['SIP_CONTACT3_CALL_WAIT'];
  $insertsql.=",SIP_CONTACT3_FORWARD_TYPE";
  $insertsql2.="','".$values['SIP_CONTACT3_FORWARD_TYPE'];
  $insertsql.=",SIP_CONTACT3_FORWARD_NUMBER";
  $insertsql2.="','".$values['SIP_CONTACT3_FORWARD_NUMBER'];
  $insertsql.=",SIP_CONTACT3_VM_NUM";
  $insertsql2.="','".$values['SIP_CONTACT3_VM_NUM'];
  $insertsql.=",P2_HOT_LINE_NUM";
  $insertsql2.="','".$values['P2_HOT_LINE_NUM'];
  $insertsql.=",P2_DIAL_PLAN";
  $insertsql2.="','".$values['P2_DIAL_PLAN'];
  $insertsql.=",P2_RING_TYPE";
  $insertsql2.="','".$values['P2_RING_TYPE'];
  $insertsql.=",L2_AUTO_ANSWER";
  $insertsql2.="','".$values['L2_AUTO_ANSWER'];




  $insertsql.=",SIP_LOCAL_PORT";
  $insertsql2.="','".$values['SIP_LOCAL_PORT'];
  $insertsql.=",SIP_OPERATION_MODE";
  $insertsql2.="','".$values['SIP_OPERATION_MODE'];
  $insertsql.=",SIP_PROTOCOL_MODE";
  $insertsql2.="','".$values['SIP_PROTOCOL_MODE'];
  $insertsql.=",SIP_MWI";
  $insertsql2.="','".$values['SIP_MWI'];
  $insertsql.=",SIP_DISABLE_CALL_WAIT";
  $insertsql2.="','".$values['SIP_DISABLE_CALL_WAIT'];
  $insertsql.=",SIP_NO_ALIVE";
  $insertsql2.="','".$values['SIP_NO_ALIVE'];
  $insertsql.=",SIP_P2P_ENABLE";
  $insertsql2.="','".$values['SIP_P2P_ENABLE'];
  $insertsql.=",SIP_VIRTUAL_RB_TONE";
  $insertsql2.="','".$values['SIP_VIRTUAL_RB_TONE'];
  $insertsql.=",SIP_ROUTE_FIELD_DISABLE";
  $insertsql2.="','".$values['SIP_ROUTE_FIELD_DISABLE'];
  $insertsql.=",SIP_MUSIC_ON_HOLD";
  $insertsql2.="','".$values['SIP_MUSIC_ON_HOLD'];
  $insertsql.=",SIP_MSG_POUND_AS_POUND";
  $insertsql2.="','".$values['SIP_MSG_POUND_AS_POUND'];
  $insertsql.=",INBAND_DTMF";
  $insertsql2.="','".$values['INBAND_DTMF'];
  $insertsql.=",SIP_OUTBAND_DTMF_TYPE";
  $insertsql2.="','".$values['SIP_OUTBAND_DTMF_TYPE'];
  $insertsql.=",DTMF_PAYLOAD_TYPE";
  $insertsql2.="','".$values['DTMF_PAYLOAD_TYPE'];
  $insertsql.=",SIP_QOS";
  $insertsql2.="','".$values['SIP_QOS'];
  $insertsql.=",SIP_TOS";
  $insertsql2.="','".$values['SIP_TOS'];
  $insertsql.=",SIP_DIFFSERV";
  $insertsql2.="','".$values['SIP_DIFFSERV'];
  $insertsql.=",SIP_CRYPT";
  $insertsql2.="','".$values['SIP_CRYPT'];
  $insertsql.=",SIP_RC4_KEY";
  $insertsql2.="','".$values['SIP_RC4_KEY'];
  $insertsql.=",ECM_CRYPT_KEY";
  $insertsql2.="','".$values['ECM_CRYPT_KEY'];
  $insertsql.=",SIP_ET263_CRYPT_TYPE";
  $insertsql2.="','".$values['SIP_ET263_CRYPT_TYPE'];
  $insertsql.=",SIP_ET263_CRYPT_DEP";
  $insertsql2.="','".$values['SIP_ET263_CRYPT_DEP'];
  $insertsql.=",SIP_NAT_TRAVERSAL";
  $insertsql2.="','".$values['SIP_NAT_TRAVERSAL'];
  $insertsql.=",SIP_STUN_SERVER";
  $insertsql2.="','".$values['SIP_STUN_SERVER'];
  $insertsql.=",SIP_RELAY_SERVER";
  $insertsql2.="','".$values['SIP_RELAY_SERVER'];
  $insertsql.=",SIP_RELAY_PORT";
  $insertsql2.="','".$values['SIP_RELAY_PORT'];
  $insertsql.=",SIP_RELAY_USER";
  $insertsql2.="','".$values['SIP_RELAY_USER'];
  $insertsql.=",SIP_RELAY_PASSWD";
  $insertsql2.="','".$values['SIP_RELAY_PASSWD'];
  $insertsql.=",SIP_RELAY_ENCRYPT";
  $insertsql2.="','".$values['SIP_RELAY_ENCRYPT'];
  $insertsql.=",SIP_RELAY_SERVER1";
  $insertsql2.="','".$values['SIP_RELAY_SERVER1'];
  $insertsql.=",SIP_RELAY_SERVER2";
  $insertsql2.="','".$values['SIP_RELAY_SERVER2'];
  $insertsql.=",SIP_RELAY_SERVER3";
  $insertsql2.="','".$values['SIP_RELAY_SERVER3'];
  $insertsql.=",SIP_RELAY_SERVER4";
  $insertsql2.="','".$values['SIP_RELAY_SERVER4'];


  $insertsql.=",RTP_PORT";
  $insertsql2.="','".$values['RTP_PORT'];
  $insertsql.=",PACKETIZE_PERIOD";
  $insertsql2.="','".$values['PACKETIZE_PERIOD'];
  $insertsql.=",VPDSP_JB_MODE";
  $insertsql2.="','".$values['VPDSP_JB_MODE'];
  $insertsql.=",VPDSP_ADPT_MIN_JITTER";
  $insertsql2.="','".$values['VPDSP_ADPT_MIN_JITTER'];
  $insertsql.=",VPDSP_ADPT_MAX_JITTER";
  $insertsql2.="','".$values['VPDSP_ADPT_MAX_JITTER'];
  $insertsql.=",VPDSP_SEQ_MIN_JITTER";
  $insertsql2.="','".$values['VPDSP_SEQ_MIN_JITTER'];
  $insertsql.=",VPDSP_SEQ_MAX_JITTER";
  $insertsql2.="','".$values['VPDSP_SEQ_MAX_JITTER'];
  $insertsql.=",VPDSP_MIN_JITTER";
  $insertsql2.="','".$values['VPDSP_MIN_JITTER'];
  $insertsql.=",RTP_QOS";
  $insertsql2.="','".$values['RTP_QOS'];
  $insertsql.=",RTP_TOS";
  $insertsql2.="','".$values['RTP_TOS'];
  $insertsql.=",RTP_DIFFSERV";
  $insertsql2.="','".$values['RTP_DIFFSERV'];
  $insertsql.=",MG_CRYPT";
  $insertsql2.="','".$values['MG_CRYPT'];
  $insertsql.=",MG_RC4_KEY";
  $insertsql2.="','".$values['MG_RC4_KEY'];
  $insertsql.=",MG_ET263_CRYPT_TYPE";
  $insertsql2.="','".$values['MG_ET263_CRYPT_TYPE'];
  $insertsql.=",MG_ET263_CRYPT_DEP";
  $insertsql2.="','".$values['MG_ET263_CRYPT_DEP'];
  $insertsql.=",SYMMETRIC_RTP";
  $insertsql2.="','".$values['SYMMETRIC_RTP'];
  $insertsql.=",MG_NAT_TRAVERSAL";
  $insertsql2.="','".$values['MG_NAT_TRAVERSAL'];
  $insertsql.=",MG_STUN_SERVER";
  $insertsql2.="','".$values['MG_STUN_SERVER'];
  $insertsql.=",MG_PORTFWD_TYPE";
  $insertsql2.="','".$values['MG_PORTFWD_TYPE'];
  $insertsql.=",MG_PORTFWD_GW";
  $insertsql2.="','".$values['MG_PORTFWD_GW'];
  $insertsql.=",MG_RELAY_SERVER";
  $insertsql2.="','".$values['MG_RELAY_SERVER'];
  $insertsql.=",MG_RELAY_PORT";
  $insertsql2.="','".$values['MG_RELAY_PORT'];
  $insertsql.=",MG_RELAY_USER";
  $insertsql2.="','".$values['MG_RELAY_USER'];
  $insertsql.=",MG_RELAY_PASSWD";
  $insertsql2.="','".$values['MG_RELAY_PASSWD'];
  $insertsql.=",MG_RELAY_ENCRYPT";
  $insertsql2.="','".$values['MG_RELAY_ENCRYPT'];
  $insertsql.=",MG_RELAY_MODE";
  $insertsql2.="','".$values['MG_RELAY_MODE'];
  $insertsql.=",MG_RELAY_SERVER1";
  $insertsql2.="','".$values['MG_RELAY_SERVER1'];
  $insertsql.=",MG_RELAY_SERVER2";
  $insertsql2.="','".$values['MG_RELAY_SERVER2'];
  $insertsql.=",MG_RELAY_SERVER3";
  $insertsql2.="','".$values['MG_RELAY_SERVER3'];
  $insertsql.=",MG_RELAY_SERVER4";
  $insertsql2.="','".$values['MG_RELAY_SERVER4'];
  $insertsql.=",VPDSP_SIDE_TONE";
  $insertsql2.="','".$values['VPDSP_SIDE_TONE'];

  $insertsql.=",L1_AUTO_ANSWER_NUM_1";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_1'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_2";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_2'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_3";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_3'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_4";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_4'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_5";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_5'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_6";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_6'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_7";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_7'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_8";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_8'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_9";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_9'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_10";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_10'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_11";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_11'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_12";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_12'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_13";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_13'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_14";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_14'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_15";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_15'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_16";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_16'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_17";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_17'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_18";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_18'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_19";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_19'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_20";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_20'];

  $insertsql.=",L2_AUTO_ANSWER_NUM_1";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_1'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_2";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_2'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_3";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_3'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_4";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_4'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_5";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_5'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_6";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_6'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_7";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_7'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_8";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_8'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_9";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_9'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_10";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_10'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_11";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_11'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_12";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_12'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_13";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_13'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_14";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_14'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_15";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_15'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_16";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_16'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_17";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_17'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_18";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_18'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_19";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_19'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_20";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_20'];

  $insertsql.=",P2_PREFER_CODEC1";
  $insertsql2.="','".$values['P2_PREFER_CODEC1'];
  $insertsql.=",P2_CODEC1_DISABLE";
  $insertsql2.="','".$values['P2_CODEC1_DISABLE'];
  $insertsql.=",P2_PREFER_CODEC2";
  $insertsql2.="','".$values['P2_PREFER_CODEC2'];
  $insertsql.=",P2_CODEC2_DISABLE";
  $insertsql2.="','".$values['P2_CODEC2_DISABLE'];
  $insertsql.=",P2_PREFER_CODEC3";
  $insertsql2.="','".$values['P2_PREFER_CODEC3'];
  $insertsql.=",P2_CODEC3_DISABLE";
  $insertsql2.="','".$values['P2_CODEC3_DISABLE'];
  $insertsql.=",P2_PREFER_CODEC4";
  $insertsql2.="','".$values['P2_PREFER_CODEC4'];
  $insertsql.=",P2_CODEC4_DISABLE";
  $insertsql2.="','".$values['P2_CODEC4_DISABLE'];
  $insertsql.=",P2_PREFER_CODEC5";
  $insertsql2.="','".$values['P2_PREFER_CODEC5'];
  $insertsql.=",P2_CODEC5_DISABLE";
  $insertsql2.="','".$values['P2_CODEC5_DISABLE'];
  $insertsql.=",P2_PREFER_CODEC6";
  $insertsql2.="','".$values['P2_PREFER_CODEC6'];
  $insertsql.=",P2_CODEC6_DISABLE";
  $insertsql2.="','".$values['P2_CODEC6_DISABLE'];
  $insertsql.=",P2_PREFER_CODEC7";
  $insertsql2.="','".$values['P2_PREFER_CODEC7'];
  $insertsql.=",P2_CODEC7_DISABLE";
  $insertsql2.="','".$values['P2_CODEC7_DISABLE'];

  $insertsql.=",P3_PREFER_CODEC1";
  $insertsql2.="','".$values['P3_PREFER_CODEC1'];
  $insertsql.=",P3_CODEC1_DISABLE";
  $insertsql2.="','".$values['P3_CODEC1_DISABLE'];
  $insertsql.=",P3_PREFER_CODEC2";
  $insertsql2.="','".$values['P3_PREFER_CODEC2'];
  $insertsql.=",P3_CODEC2_DISABLE";
  $insertsql2.="','".$values['P3_CODEC2_DISABLE'];
  $insertsql.=",P3_PREFER_CODEC3";
  $insertsql2.="','".$values['P3_PREFER_CODEC3'];
  $insertsql.=",P3_CODEC3_DISABLE";
  $insertsql2.="','".$values['P3_CODEC3_DISABLE'];
  $insertsql.=",P3_PREFER_CODEC4";
  $insertsql2.="','".$values['P3_PREFER_CODEC4'];
  $insertsql.=",P3_CODEC4_DISABLE";
  $insertsql2.="','".$values['P3_CODEC4_DISABLE'];
  $insertsql.=",P3_PREFER_CODEC5";
  $insertsql2.="','".$values['P3_PREFER_CODEC5'];
  $insertsql.=",P3_CODEC5_DISABLE";
  $insertsql2.="','".$values['P3_CODEC5_DISABLE'];
  $insertsql.=",P3_PREFER_CODEC6";
  $insertsql2.="','".$values['P3_PREFER_CODEC6'];
  $insertsql.=",P3_CODEC6_DISABLE";
  $insertsql2.="','".$values['P3_CODEC6_DISABLE'];
  $insertsql.=",P3_PREFER_CODEC7";
  $insertsql2.="','".$values['P3_PREFER_CODEC7'];
  $insertsql.=",P3_CODEC7_DISABLE";
  $insertsql2.="','".$values['P3_CODEC7_DISABLE'];

  $insertsql.=",SIP_KEEPALIVE_INTERVAL";
  $insertsql2.="','".$values['SIP_KEEPALIVE_INTERVAL'];

  $insertsql.=",SIP_FAIL_RETRY_INTERVAL";
  $insertsql2.="','".$values['SIP_FAIL_RETRY_INTERVAL'];

 //?<8f>ˉè<83>??2??<9c><89>?-¤?<8f><82>?<95>?
//  $insertsql.=",TELLINE";
//  $insertsql2.="','".$values['TELLINE'];
  $insertsql.=",SIP_REGISTER_EXPIRY";
  $insertsql2.="','".$values['SIP_REGISTER_EXPIRY'];
  $insertsql.=",SIP_SUBSCRIBE_EXPIRY";
  $insertsql2.="','".$values['SIP_SUBSCRIBE_EXPIRY'];


  $insertsql.=",UNANSWER_FW_EXP";
  $insertsql2.="','".$values['UNANSWER_FW_EXP'];
  $insertsql.=",UNANSWER_EXP";
  $insertsql2.="','".$values['UNANSWER_EXP'];
  $insertsql.=",NON_INVITE_TS_EXP";
  $insertsql2.="','".$values['NON_INVITE_TS_EXP'];                                                                
  $insertsql.=",INVITE_TS_EXP";                                                                                   
  $insertsql2.="','".$values['INVITE_TS_EXP'];                                                                    
  $insertsql.=",RETRANSMIT_T1";                                                                                   
  $insertsql2.="','".$values['RETRANSMIT_T1'];                                                                    
  $insertsql.=",RETRANSMIT_T2";                                                                                   
  $insertsql2.="','".$values['RETRANSMIT_T2'];  

  $insertsql.=",AUTOCFG";
  $insertsql2.="','".$values['AUTOCFG'];
  $insertsql.=",AUTOCFG_SERVER";
  $insertsql2.="','".$values['AUTOCFG_SERVER'];
  $insertsql.=",AUTOCFG_REFRESH";
  $insertsql2.="','".$values['AUTOCFG_REFRESH'];
  $insertsql.=",RADMIN_ENABLE";
  $insertsql2.="','".$values['RADMIN_ENABLE'];
  $insertsql.=",RADMIN_SERVER";
  $insertsql2.="','".$values['RADMIN_SERVER'];
  $insertsql.=",RADMIN_PORT";
  $insertsql2.="','".$values['RADMIN_PORT'];
  $insertsql.=",RADMIN_ID";
  $insertsql2.="','".$values['RADMIN_ID'];
  $insertsql.=",RADMIN_KEY";
  $insertsql2.="','".$values['RADMIN_KEY'];

?>
