<?php
  $values['SIP_WORK_MODE'] = $_POST['sip_work_mode'] ;
  $updatesql.=",SIP_WORK_MODE='".$values['SIP_WORK_MODE']."'";
if($values['SIP_WORK_MODE'] == 'BSVR'):
  $values['SIP_CONTACT0_DIAL_DIGITS'] = $_POST['sip_contact1_number'] ;
  $updatesql.=",SIP_CONTACT0_DIAL_DIGITS='".$values['SIP_CONTACT0_DIAL_DIGITS']."'";
  $values['SIP_CONTACT0_LOGIN'] = $_POST['sip_contact1_auth_id'] ;
  $updatesql.=",SIP_CONTACT0_LOGIN='".$values['SIP_CONTACT0_LOGIN']."'";
  $values['SIP_CONTACT0_PASSWD'] = $_POST['sip_contact1_auth_passwd'] ;
  $updatesql.=",SIP_CONTACT0_PASSWD='".$values['SIP_CONTACT0_PASSWD']."'";
  $values['SIP_CONTACT0_DISPLAY_NAME'] = $_POST['sip_contact1_display_name'] ;
  $updatesql.=",SIP_CONTACT0_DISPLAY_NAME='".$values['SIP_CONTACT0_DISPLAY_NAME']."'";
  $values['C1_RING_TYPE'] = $_POST['contact1_ring_type'] ;
  $updatesql.=",C1_RING_TYPE='".$values['C1_RING_TYPE']."'";
  $values['SIP_CONTACT0_DIAL_DIGITS_2'] = $_POST['sip_contact2_number'] ;
  $updatesql.=",SIP_CONTACT0_DIAL_DIGITS_2='".$values['SIP_CONTACT0_DIAL_DIGITS_2']."'";
  $values['SIP_CONTACT0_LOGIN_2'] = $_POST['sip_contact2_auth_id'] ;
  $updatesql.=",SIP_CONTACT0_LOGIN_2='".$values['SIP_CONTACT0_LOGIN_2']."'";
  $values['SIP_CONTACT0_PASSWD_2'] = $_POST['sip_contact2_auth_passwd'] ;
  $updatesql.=",SIP_CONTACT0_PASSWD_2='".$values['SIP_CONTACT0_PASSWD_2']."'";
  $values['SIP_CONTACT0_DISPLAY_NAME_2'] = $_POST['sip_contact2_display_name'] ;
  $updatesql.=",SIP_CONTACT0_DISPLAY_NAME_2='".$values['SIP_CONTACT0_DISPLAY_NAME_2']."'";
  $values['C2_RING_TYPE'] = $_POST['contact2_ring_type'] ;
  $updatesql.=",C2_RING_TYPE='".$values['C2_RING_TYPE']."'";
  $values['SIP_CONTACT0_DIAL_DIGITS_3'] = $_POST['sip_contact3_number'] ;
  $updatesql.=",SIP_CONTACT0_DIAL_DIGITS_3='".$values['SIP_CONTACT0_DIAL_DIGITS_3']."'";
  $values['SIP_CONTACT0_LOGIN_3'] = $_POST['sip_contact3_auth_id'] ;
  $updatesql.=",SIP_CONTACT0_LOGIN_3='".$values['SIP_CONTACT0_LOGIN_3']."'";
  $values['SIP_CONTACT0_PASSWD_3'] = $_POST['sip_contact3_auth_passwd'] ;
  $updatesql.=",SIP_CONTACT0_PASSWD_3='".$values['SIP_CONTACT0_PASSWD_3']."'";
  $values['SIP_CONTACT0_DISPLAY_NAME_3'] = $_POST['sip_contact3_display_name'] ;
  $updatesql.=",SIP_CONTACT0_DISPLAY_NAME_3='".$values['SIP_CONTACT0_DISPLAY_NAME_3']."'";
  $values['C3_RING_TYPE'] = $_POST['contact3_ring_type'] ;
  $updatesql.=",C3_RING_TYPE='".$values['C3_RING_TYPE']."'";
  $values['SIP_CONTACT0_DIAL_DIGITS_4'] = $_POST['sip_contact4_number'] ;
  $updatesql.=",SIP_CONTACT0_DIAL_DIGITS_4='".$values['SIP_CONTACT0_DIAL_DIGITS_4']."'";
  $values['SIP_CONTACT0_LOGIN_4'] = $_POST['sip_contact4_auth_id'] ;
  $updatesql.=",SIP_CONTACT0_LOGIN_4='".$values['SIP_CONTACT0_LOGIN_4']."'";
  $values['SIP_CONTACT0_PASSWD_4'] = $_POST['sip_contact4_auth_passwd'] ;
  $updatesql.=",SIP_CONTACT0_PASSWD_4='".$values['SIP_CONTACT0_PASSWD_4']."'";
  $values['SIP_CONTACT0_DISPLAY_NAME_4'] = $_POST['sip_contact4_display_name'] ;
  $updatesql.=",SIP_CONTACT0_DISPLAY_NAME_4='".$values['SIP_CONTACT0_DISPLAY_NAME_4']."'";
  $values['C4_RING_TYPE'] = $_POST['contact4_ring_type'] ;
  $updatesql.=",C4_RING_TYPE='".$values['C4_RING_TYPE']."'";
  $values['SIP_CONTACT0_PROXY'] = $_POST['sip_proxy'] ;
  $updatesql.=",SIP_CONTACT0_PROXY='".$values['SIP_CONTACT0_PROXY']."'";
  $values['SIP_CONTACT0_SERVER'] = $_POST['sip_registrar'] ;
  $updatesql.=",SIP_CONTACT0_SERVER='".$values['SIP_CONTACT0_SERVER']."'";
  $values['SIP_CONTACT0_EXPIRED'] = $_POST['sip_register_expired'] ;
  $updatesql.=",SIP_CONTACT0_EXPIRED='".$values['SIP_CONTACT0_EXPIRED']."'";
  $values['SIP_CONTACT0_OUTBOUND_PROXY'] = $_POST['sip_outbound_proxy'] ;
  $updatesql.=",SIP_CONTACT0_OUTBOUND_PROXY='".$values['SIP_CONTACT0_OUTBOUND_PROXY']."'";
  $values['SIP_CONTACT0_HOME_DOMAIN'] = $_POST['sip_home_domain'] ;
  $updatesql.=",SIP_CONTACT0_HOME_DOMAIN='".$values['SIP_CONTACT0_HOME_DOMAIN']."'";
  $values['SIP_CONTACT0_CALL_WAIT'] = $_POST['sip_call_wait']=='on'?'1':'0';
  $updatesql.=",SIP_CONTACT0_CALL_WAIT='".$values['SIP_CONTACT0_CALL_WAIT']."'";
  $values['SIP_CONTACT0_FORWARD_TYPE'] = $_POST['sip_fwd_type'] ;
  $updatesql.=",SIP_CONTACT0_FORWARD_TYPE='".$values['SIP_CONTACT0_FORWARD_TYPE']."'";
  $values['SIP_CONTACT0_FORWARD_NUMBER'] = $_POST['sip_fwd_num'] ;
  $updatesql.=",SIP_CONTACT0_FORWARD_NUMBER='".$values['SIP_CONTACT0_FORWARD_NUMBER']."'";
  $values['SIP_CONTACT0_VM_NUM'] = $_POST['sip_vm_num'] ;
  $updatesql.=",SIP_CONTACT0_VM_NUM='".$values['SIP_CONTACT0_VM_NUM']."'";
  $values['P0_HOT_LINE_NUM'] = $_POST['sip_hot_line_num'] ;
  $updatesql.=",P0_HOT_LINE_NUM='".$values['P0_HOT_LINE_NUM']."'";
  $values['P0_DIAL_PLAN'] = $_POST['sip_dial_plan'] ;
  $updatesql.=",P0_DIAL_PLAN='".$values['P0_DIAL_PLAN']."'";
  $values['USE_BACKUP_SIP_SVR'] = $_POST['sip_backup_server']=='on'?'1':'0';
  $updatesql.=",USE_BACKUP_SIP_SVR='".$values['USE_BACKUP_SIP_SVR']."'";
if($values['USE_BACKUP_SIP_SVR'] == 1):
  $values['SIP_CONTACT1_PROXY'] = $_POST['sip_backup_proxy'] ;
  $updatesql.=",SIP_CONTACT1_PROXY='".$values['SIP_CONTACT1_PROXY']."'";
  $values['SIP_CONTACT1_SERVER'] = $_POST['sip_backup_registrar'] ;
  $updatesql.=",SIP_CONTACT1_SERVER='".$values['SIP_CONTACT1_SERVER']."'";
  $values['SIP_CONTACT1_OUTBOUND_PROXY'] = $_POST['sip_backup_outbound_proxy'] ;
  $updatesql.=",SIP_CONTACT1_OUTBOUND_PROXY='".$values['SIP_CONTACT1_OUTBOUND_PROXY']."'";
  $values['SIP_CONTACT1_HOME_DOMAIN'] = $_POST['sip_backup_home_domain'] ;
  $updatesql.=",SIP_CONTACT1_HOME_DOMAIN='".$values['SIP_CONTACT1_HOME_DOMAIN']."'";
endif; 
endif; 
if($values['SIP_WORK_MODE'] == 'MSVR'):
  $values['SIP_CONTACT2_DIAL_DIGITS'] = $_POST['sip_profile1_number'] ;
  $updatesql.=",SIP_CONTACT2_DIAL_DIGITS='".$values['SIP_CONTACT2_DIAL_DIGITS']."'";
  $values['SIP_CONTACT2_DISPLAY_NAME'] = $_POST['sip_profile1_display_name'] ;
  $updatesql.=",SIP_CONTACT2_DISPLAY_NAME='".$values['SIP_CONTACT2_DISPLAY_NAME']."'";
  $values['SIP_CONTACT2_PROXY'] = $_POST['sip_profile1_proxy'] ;
  $updatesql.=",SIP_CONTACT2_PROXY='".$values['SIP_CONTACT2_PROXY']."'";
  $values['SIP_CONTACT2_SERVER'] = $_POST['sip_profile1_registrar'] ;
  $updatesql.=",SIP_CONTACT2_SERVER='".$values['SIP_CONTACT2_SERVER']."'";
  $values['SIP_CONTACT2_EXPIRED'] = $_POST['sip_profile1_register_expired'] ;
  $updatesql.=",SIP_CONTACT2_EXPIRED='".$values['SIP_CONTACT2_EXPIRED']."'";
  $values['SIP_CONTACT2_OUTBOUND_PROXY'] = $_POST['sip_profile1_outbound_proxy'] ;
  $updatesql.=",SIP_CONTACT2_OUTBOUND_PROXY='".$values['SIP_CONTACT2_OUTBOUND_PROXY']."'";
  $values['SIP_CONTACT2_HOME_DOMAIN'] = $_POST['sip_profile1_home_domain'] ;
  $updatesql.=",SIP_CONTACT2_HOME_DOMAIN='".$values['SIP_CONTACT2_HOME_DOMAIN']."'";
  $values['SIP_CONTACT2_LOGIN'] = $_POST['sip_profile1_auth_id'] ;
  $updatesql.=",SIP_CONTACT2_LOGIN='".$values['SIP_CONTACT2_LOGIN']."'";
  $values['SIP_CONTACT2_PASSWD'] = $_POST['sip_profile1_auth_passwd'] ;
  $updatesql.=",SIP_CONTACT2_PASSWD='".$values['SIP_CONTACT2_PASSWD']."'";
  $values['SIP_CONTACT2_CALL_WAIT'] = $_POST['sip_profile1_call_wait']=='on'?'1':'0';
  $updatesql.=",SIP_CONTACT2_CALL_WAIT='".$values['SIP_CONTACT2_CALL_WAIT']."'";
  $values['SIP_CONTACT2_FORWARD_TYPE'] = $_POST['sip_profile1_fwd_type'] ;
  $updatesql.=",SIP_CONTACT2_FORWARD_TYPE='".$values['SIP_CONTACT2_FORWARD_TYPE']."'";
  $values['SIP_CONTACT2_FORWARD_NUMBER'] = $_POST['sip_profile1_fwd_num'] ;
  $updatesql.=",SIP_CONTACT2_FORWARD_NUMBER='".$values['SIP_CONTACT2_FORWARD_NUMBER']."'";
  $values['SIP_CONTACT2_VM_NUM'] = $_POST['sip_profile1_vm_num'] ;
  $updatesql.=",SIP_CONTACT2_VM_NUM='".$values['SIP_CONTACT2_VM_NUM']."'";
  $values['P1_HOT_LINE_NUM'] = $_POST['sip_profile1_hot_line_num'] ;
  $updatesql.=",P1_HOT_LINE_NUM='".$values['P1_HOT_LINE_NUM']."'";
  $values['P1_DIAL_PLAN'] = $_POST['sip_profile1_dial_plan'] ;
  $updatesql.=",P1_DIAL_PLAN='".$values['P1_DIAL_PLAN']."'";
  $values['P1_RING_TYPE'] = $_POST['profile1_ring_type'] ;
  $updatesql.=",P1_RING_TYPE='".$values['P1_RING_TYPE']."'";
if($values['AUTO_ANSWER'] != '0'):
  $values['L1_AUTO_ANSWER'] = $_POST['l1_auto_answer_mode'] ;
  $updatesql.=",L1_AUTO_ANSWER='".$values['L1_AUTO_ANSWER']."'";
endif; 
if($values['L1_AUTO_ANSWER'] == 'LIST'):
endif; 
  $values['SIP_CONTACT3_DIAL_DIGITS'] = $_POST['sip_profile2_number'] ;
  $updatesql.=",SIP_CONTACT3_DIAL_DIGITS='".$values['SIP_CONTACT3_DIAL_DIGITS']."'";
  $values['SIP_CONTACT3_DISPLAY_NAME'] = $_POST['sip_profile2_display_name'] ;
  $updatesql.=",SIP_CONTACT3_DISPLAY_NAME='".$values['SIP_CONTACT3_DISPLAY_NAME']."'";
  $values['SIP_CONTACT3_PROXY'] = $_POST['sip_profile2_proxy'] ;
  $updatesql.=",SIP_CONTACT3_PROXY='".$values['SIP_CONTACT3_PROXY']."'";
  $values['SIP_CONTACT3_SERVER'] = $_POST['sip_profile2_registrar'] ;
  $updatesql.=",SIP_CONTACT3_SERVER='".$values['SIP_CONTACT3_SERVER']."'";
  $values['SIP_CONTACT3_EXPIRED'] = $_POST['sip_profile2_register_expired'] ;
  $updatesql.=",SIP_CONTACT3_EXPIRED='".$values['SIP_CONTACT3_EXPIRED']."'";
  $values['SIP_CONTACT3_OUTBOUND_PROXY'] = $_POST['sip_profile2_outbound_proxy'] ;
  $updatesql.=",SIP_CONTACT3_OUTBOUND_PROXY='".$values['SIP_CONTACT3_OUTBOUND_PROXY']."'";
  $values['SIP_CONTACT3_HOME_DOMAIN'] = $_POST['sip_profile2_home_domain'] ;
  $updatesql.=",SIP_CONTACT3_HOME_DOMAIN='".$values['SIP_CONTACT3_HOME_DOMAIN']."'";
  $values['SIP_CONTACT3_LOGIN'] = $_POST['sip_profile2_auth_id'] ;
  $updatesql.=",SIP_CONTACT3_LOGIN='".$values['SIP_CONTACT3_LOGIN']."'";
  $values['SIP_CONTACT3_PASSWD'] = $_POST['sip_profile2_auth_passwd'] ;
  $updatesql.=",SIP_CONTACT3_PASSWD='".$values['SIP_CONTACT3_PASSWD']."'";
  $values['SIP_CONTACT3_CALL_WAIT'] = $_POST['sip_profile2_call_wait']=='on'?'1':'0';
  $updatesql.=",SIP_CONTACT3_CALL_WAIT='".$values['SIP_CONTACT3_CALL_WAIT']."'";
  $values['SIP_CONTACT3_FORWARD_TYPE'] = $_POST['sip_profile2_fwd_type'] ;
  $updatesql.=",SIP_CONTACT3_FORWARD_TYPE='".$values['SIP_CONTACT3_FORWARD_TYPE']."'";
  $values['SIP_CONTACT3_FORWARD_NUMBER'] = $_POST['sip_profile2_fwd_num'] ;
  $updatesql.=",SIP_CONTACT3_FORWARD_NUMBER='".$values['SIP_CONTACT3_FORWARD_NUMBER']."'";
  $values['SIP_CONTACT3_VM_NUM'] = $_POST['sip_profile2_vm_num'] ;
  $updatesql.=",SIP_CONTACT3_VM_NUM='".$values['SIP_CONTACT3_VM_NUM']."'";
  $values['P2_HOT_LINE_NUM'] = $_POST['sip_profile2_hot_line_num'] ;
  $updatesql.=",P2_HOT_LINE_NUM='".$values['P2_HOT_LINE_NUM']."'";
  $values['P2_DIAL_PLAN'] = $_POST['sip_profile2_dial_plan'] ;
  $updatesql.=",P2_DIAL_PLAN='".$values['P2_DIAL_PLAN']."'";
  $values['P2_RING_TYPE'] = $_POST['profile2_ring_type'] ;
  $updatesql.=",P2_RING_TYPE='".$values['P2_RING_TYPE']."'";
if($values['AUTO_ANSWER'] != '0'):
  $values['L2_AUTO_ANSWER'] = $_POST['l2_auto_answer_mode'] ;
  $updatesql.=",L2_AUTO_ANSWER='".$values['L2_AUTO_ANSWER']."'";
endif; 
if($values['L2_AUTO_ANSWER'] == 'LIST'):
endif; 
  $values['SIP_CONTACT4_DIAL_DIGITS'] = $_POST['sip_profile3_number'] ;
  $updatesql.=",SIP_CONTACT4_DIAL_DIGITS='".$values['SIP_CONTACT4_DIAL_DIGITS']."'";
  $values['SIP_CONTACT4_DISPLAY_NAME'] = $_POST['sip_profile3_display_name'] ;
  $updatesql.=",SIP_CONTACT4_DISPLAY_NAME='".$values['SIP_CONTACT4_DISPLAY_NAME']."'";
  $values['SIP_CONTACT4_PROXY'] = $_POST['sip_profile3_proxy'] ;
  $updatesql.=",SIP_CONTACT4_PROXY='".$values['SIP_CONTACT4_PROXY']."'";
  $values['SIP_CONTACT4_SERVER'] = $_POST['sip_profile3_registrar'] ;
  $updatesql.=",SIP_CONTACT4_SERVER='".$values['SIP_CONTACT4_SERVER']."'";
  $values['SIP_CONTACT4_EXPIRED'] = $_POST['sip_profile3_register_expired'] ;
  $updatesql.=",SIP_CONTACT4_EXPIRED='".$values['SIP_CONTACT4_EXPIRED']."'";
  $values['SIP_CONTACT4_OUTBOUND_PROXY'] = $_POST['sip_profile3_outbound_proxy'] ;
  $updatesql.=",SIP_CONTACT4_OUTBOUND_PROXY='".$values['SIP_CONTACT4_OUTBOUND_PROXY']."'";
  $values['SIP_CONTACT4_HOME_DOMAIN'] = $_POST['sip_profile3_home_domain'] ;
  $updatesql.=",SIP_CONTACT4_HOME_DOMAIN='".$values['SIP_CONTACT4_HOME_DOMAIN']."'";
  $values['SIP_CONTACT4_LOGIN'] = $_POST['sip_profile3_auth_id'] ;
  $updatesql.=",SIP_CONTACT4_LOGIN='".$values['SIP_CONTACT4_LOGIN']."'";
  $values['SIP_CONTACT4_PASSWD'] = $_POST['sip_profile3_auth_passwd'] ;
  $updatesql.=",SIP_CONTACT4_PASSWD='".$values['SIP_CONTACT4_PASSWD']."'";
  $values['SIP_CONTACT4_CALL_WAIT'] = $_POST['sip_profile3_call_wait']=='on'?'1':'0';
  $updatesql.=",SIP_CONTACT4_CALL_WAIT='".$values['SIP_CONTACT4_CALL_WAIT']."'";
  $values['SIP_CONTACT4_FORWARD_TYPE'] = $_POST['sip_profile3_fwd_type'] ;
  $updatesql.=",SIP_CONTACT4_FORWARD_TYPE='".$values['SIP_CONTACT4_FORWARD_TYPE']."'";
  $values['SIP_CONTACT4_FORWARD_NUMBER'] = $_POST['sip_profile3_fwd_num'] ;
  $updatesql.=",SIP_CONTACT4_FORWARD_NUMBER='".$values['SIP_CONTACT4_FORWARD_NUMBER']."'";
  $values['SIP_CONTACT4_VM_NUM'] = $_POST['sip_profile3_vm_num'] ;
  $updatesql.=",SIP_CONTACT4_VM_NUM='".$values['SIP_CONTACT4_VM_NUM']."'";
  $values['P3_HOT_LINE_NUM'] = $_POST['sip_profile3_hot_line_num'] ;
  $updatesql.=",P3_HOT_LINE_NUM='".$values['P3_HOT_LINE_NUM']."'";
  $values['P3_DIAL_PLAN'] = $_POST['sip_profile3_dial_plan'] ;
  $updatesql.=",P3_DIAL_PLAN='".$values['P3_DIAL_PLAN']."'";
  $values['P3_RING_TYPE'] = $_POST['profile3_ring_type'] ;
  $updatesql.=",P3_RING_TYPE='".$values['P3_RING_TYPE']."'";
if($values['AUTO_ANSWER'] != '0'):
  $values['L3_AUTO_ANSWER'] = $_POST['l3_auto_answer_mode'] ;
  $updatesql.=",L3_AUTO_ANSWER='".$values['L3_AUTO_ANSWER']."'";
endif; 
if($values['L3_AUTO_ANSWER'] == 'LIST'):
endif; 
  $values['SIP_CONTACT5_DIAL_DIGITS'] = $_POST['sip_profile4_number'] ;
  $updatesql.=",SIP_CONTACT5_DIAL_DIGITS='".$values['SIP_CONTACT5_DIAL_DIGITS']."'";
  $values['SIP_CONTACT5_DISPLAY_NAME'] = $_POST['sip_profile4_display_name'] ;
  $updatesql.=",SIP_CONTACT5_DISPLAY_NAME='".$values['SIP_CONTACT5_DISPLAY_NAME']."'";
  $values['SIP_CONTACT5_PROXY'] = $_POST['sip_profile4_proxy'] ;
  $updatesql.=",SIP_CONTACT5_PROXY='".$values['SIP_CONTACT5_PROXY']."'";
  $values['SIP_CONTACT5_SERVER'] = $_POST['sip_profile4_registrar'] ;
  $updatesql.=",SIP_CONTACT5_SERVER='".$values['SIP_CONTACT5_SERVER']."'";
  $values['SIP_CONTACT5_EXPIRED'] = $_POST['sip_profile4_register_expired'] ;
  $updatesql.=",SIP_CONTACT5_EXPIRED='".$values['SIP_CONTACT5_EXPIRED']."'";
  $values['SIP_CONTACT5_OUTBOUND_PROXY'] = $_POST['sip_profile4_outbound_proxy'] ;
  $updatesql.=",SIP_CONTACT5_OUTBOUND_PROXY='".$values['SIP_CONTACT5_OUTBOUND_PROXY']."'";
  $values['SIP_CONTACT5_HOME_DOMAIN'] = $_POST['sip_profile4_home_domain'] ;
  $updatesql.=",SIP_CONTACT5_HOME_DOMAIN='".$values['SIP_CONTACT5_HOME_DOMAIN']."'";
  $values['SIP_CONTACT5_LOGIN'] = $_POST['sip_profile4_auth_id'] ;
  $updatesql.=",SIP_CONTACT5_LOGIN='".$values['SIP_CONTACT5_LOGIN']."'";
  $values['SIP_CONTACT5_PASSWD'] = $_POST['sip_profile4_auth_passwd'] ;
  $updatesql.=",SIP_CONTACT5_PASSWD='".$values['SIP_CONTACT5_PASSWD']."'";
  $values['SIP_CONTACT5_CALL_WAIT'] = $_POST['sip_profile4_call_wait']=='on'?'1':'0';
  $updatesql.=",SIP_CONTACT5_CALL_WAIT='".$values['SIP_CONTACT5_CALL_WAIT']."'";
  $values['SIP_CONTACT5_FORWARD_TYPE'] = $_POST['sip_profile4_fwd_type'] ;
  $updatesql.=",SIP_CONTACT5_FORWARD_TYPE='".$values['SIP_CONTACT5_FORWARD_TYPE']."'";
  $values['SIP_CONTACT5_FORWARD_NUMBER'] = $_POST['sip_profile4_fwd_num'] ;
  $updatesql.=",SIP_CONTACT5_FORWARD_NUMBER='".$values['SIP_CONTACT5_FORWARD_NUMBER']."'";
  $values['SIP_CONTACT5_VM_NUM'] = $_POST['sip_profile4_vm_num'] ;
  $updatesql.=",SIP_CONTACT5_VM_NUM='".$values['SIP_CONTACT5_VM_NUM']."'";
  $values['P4_HOT_LINE_NUM'] = $_POST['sip_profile4_hot_line_num'] ;
  $updatesql.=",P4_HOT_LINE_NUM='".$values['P4_HOT_LINE_NUM']."'";
  $values['P4_DIAL_PLAN'] = $_POST['sip_profile4_dial_plan'] ;
  $updatesql.=",P4_DIAL_PLAN='".$values['P4_DIAL_PLAN']."'";
  $values['P4_RING_TYPE'] = $_POST['profile4_ring_type'] ;
  $updatesql.=",P4_RING_TYPE='".$values['P4_RING_TYPE']."'";
if($values['AUTO_ANSWER'] != '0'):
  $values['L4_AUTO_ANSWER'] = $_POST['l4_auto_answer_mode'] ;
  $updatesql.=",L4_AUTO_ANSWER='".$values['L4_AUTO_ANSWER']."'";
endif; 
if($values['L4_AUTO_ANSWER'] == 'LIST'):
endif; 
endif; 


//adv
  $values['SIP_LOCAL_PORT'] = $_POST['sip_local_port'] ;
  $updatesql.=",SIP_LOCAL_PORT='".$values['SIP_LOCAL_PORT']."'";
  $values['SIP_MWI'] = $_POST['sip_mwi']=='on'?'1':'0';
  $updatesql.=",SIP_MWI='".$values['SIP_MWI']."'";
  $values['SIP_NO_ALIVE'] = $_POST['sip_no_alive']=='on'?'0':'1';
  $updatesql.=",SIP_NO_ALIVE='".$values['SIP_NO_ALIVE']."'";
  $values['SIP_P2P_ENABLE'] = $_POST['sip_p2p_enable']=='on'?'1':'0';
  $updatesql.=",SIP_P2P_ENABLE='".$values['SIP_P2P_ENABLE']."'";
  $values['INBAND_DTMF'] = $_POST['sip_dtmf_type'] ;
  $updatesql.=",INBAND_DTMF='".$values['INBAND_DTMF']."'";
if($values['INBAND_DTMF'] == '0'):
  $values['SIP_OUTBAND_DTMF_TYPE'] = $_POST['sip_outband_dtmf_type'] ;
  $updatesql.=",SIP_OUTBAND_DTMF_TYPE='".$values['SIP_OUTBAND_DTMF_TYPE']."'";
if($values['SIP_OUTBAND_DTMF_TYPE'] == '1'):
  $values['DTMF_PAYLOAD_TYPE'] = $_POST['dtmf_payload'] ;
  $updatesql.=",DTMF_PAYLOAD_TYPE='".$values['DTMF_PAYLOAD_TYPE']."'";
endif; 
endif; 
  $values['SIP_QOS'] = $_POST['sip_qos'] ;
  $updatesql.=",SIP_QOS='".$values['SIP_QOS']."'";
if($values['SIP_QOS'] == 'IPTOS'):
  $values['SIP_TOS'] = $_POST['sip_tos'] ;
  $updatesql.=",SIP_TOS='".$values['SIP_TOS']."'";
endif; 
if($values['SIP_QOS'] == 'DIFFSERV'):
  $values['SIP_DIFFSERV'] = $_POST['sip_diffserv_class'] ;
  $updatesql.=",SIP_DIFFSERV='".$values['SIP_DIFFSERV']."'";
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['SIP_NAT_TRAVERSAL'] = $_POST['sip_nat_traversal'] ;
  $updatesql.=",SIP_NAT_TRAVERSAL='".$values['SIP_NAT_TRAVERSAL']."'";
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
endif; 
if($values['SIP_NAT_TRAVERSAL'] == 'STUN'):
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['SIP_STUN_SERVER'] = $_POST['sip_stun_server'] ;
  $updatesql.=",SIP_STUN_SERVER='".$values['SIP_STUN_SERVER']."'";
endif; 
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
endif; 
if($values['SIP_NAT_TRAVERSAL'] == 'RELAY'):
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['SIP_RELAY_SERVER'] = $_POST['sip_relay_server'] ;
  $updatesql.=",SIP_RELAY_SERVER='".$values['SIP_RELAY_SERVER']."'";
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['SIP_RELAY_PORT'] = $_POST['sip_relay_port'] ;
  $updatesql.=",SIP_RELAY_PORT='".$values['SIP_RELAY_PORT']."'";
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['SIP_RELAY_USER'] = $_POST['sip_relay_user'] ;
  $updatesql.=",SIP_RELAY_USER='".$values['SIP_RELAY_USER']."'";
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['SIP_RELAY_PASSWD'] = $_POST['sip_relay_passwd'] ;
  $updatesql.=",SIP_RELAY_PASSWD='".$values['SIP_RELAY_PASSWD']."'";
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['SIP_RELAY_ENCRYPT'] = $_POST['sip_relay_encrypt']=='on'?'1':'0';
  $updatesql.=",SIP_RELAY_ENCRYPT='".$values['SIP_RELAY_ENCRYPT']."'";
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['SIP_RELAY_SERVER1'] = $_POST['sip_relay_server1'] ;
  $updatesql.=",SIP_RELAY_SERVER1='".$values['SIP_RELAY_SERVER1']."'";
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['SIP_RELAY_SERVER2'] = $_POST['sip_relay_server2'] ;
  $updatesql.=",SIP_RELAY_SERVER2='".$values['SIP_RELAY_SERVER2']."'";
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['SIP_RELAY_SERVER3'] = $_POST['sip_relay_server3'] ;
  $updatesql.=",SIP_RELAY_SERVER3='".$values['SIP_RELAY_SERVER3']."'";
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['SIP_RELAY_SERVER4'] = $_POST['sip_relay_server4'] ;
  $updatesql.=",SIP_RELAY_SERVER4='".$values['SIP_RELAY_SERVER4']."'";
endif; 
endif; 

/*siptimer*/
  $values['SIP_KEEPALIVE_INTERVAL'] = $_POST['sip_keepalive_interval'] ;
  $updatesql.=",SIP_KEEPALIVE_INTERVAL='".$values['SIP_KEEPALIVE_INTERVAL']."'";
  $values['SIP_FAIL_RETRY_INTERVAL'] = $_POST['sip_fail_retry_interval'] ;
  $updatesql.=",SIP_FAIL_RETRY_INTERVAL='".$values['SIP_FAIL_RETRY_INTERVAL']."'";
  $values['UNANSWER_FW_EXP'] = $_POST['unanswer_fw_exp'] ;
  $updatesql.=",UNANSWER_FW_EXP='".$values['UNANSWER_FW_EXP']."'";
  $values['UNANSWER_EXP'] = $_POST['unanswer_exp'] ;
  $updatesql.=",UNANSWER_EXP='".$values['UNANSWER_EXP']."'";
  $values['NON_INVITE_TS_EXP'] = $_POST['non_invite_exp'] ;
  $updatesql.=",NON_INVITE_TS_EXP='".$values['NON_INVITE_TS_EXP']."'";
  $values['INVITE_TS_EXP'] = $_POST['invite_exp'] ;
  $updatesql.=",INVITE_TS_EXP='".$values['INVITE_TS_EXP']."'";
  $values['RETRANSMIT_T1'] = $_POST['retrans_t1'] ;
  $updatesql.=",RETRANSMIT_T1='".$values['RETRANSMIT_T1']."'";
  $values['RETRANSMIT_T2'] = $_POST['retrans_t2'] ;
  $updatesql.=",RETRANSMIT_T2='".$values['RETRANSMIT_T2']."'";

//media
$values['RTP_PORT'] = $_POST['rtp_port_lower']."-".$_POST['rtp_port_upper'] ;
  //$values['RTP_PORT'] = $_POST['rtp_port_lower#'-'#rtp_port_upper'] ;
  $updatesql.=",RTP_PORT='".$values['RTP_PORT']."'";
  $values['PACKETIZE_PERIOD'] = $_POST['rtp_pkt_len'] ;
  $updatesql.=",PACKETIZE_PERIOD='".$values['PACKETIZE_PERIOD']."'";
  $values['VPDSP_JB_MODE'] = $_POST['jb_mode'] ;
  $updatesql.=",VPDSP_JB_MODE='".$values['VPDSP_JB_MODE']."'";
if($values['VPDSP_JB_MODE'] == '2'):
  $values['VPDSP_ADPT_MIN_JITTER'] = $_POST['adpt_min_jitter'] ;
  $updatesql.=",VPDSP_ADPT_MIN_JITTER='".$values['VPDSP_ADPT_MIN_JITTER']."'";
  $values['VPDSP_ADPT_MAX_JITTER'] = $_POST['adpt_max_jitter'] ;
  $updatesql.=",VPDSP_ADPT_MAX_JITTER='".$values['VPDSP_ADPT_MAX_JITTER']."'";
endif; 
if($values['VPDSP_JB_MODE'] == '1'):
  $values['VPDSP_SEQ_MIN_JITTER'] = $_POST['seq_min_jitter'] ;
  $updatesql.=",VPDSP_SEQ_MIN_JITTER='".$values['VPDSP_SEQ_MIN_JITTER']."'";
  $values['VPDSP_SEQ_MAX_JITTER'] = $_POST['seq_max_jitter'] ;
  $updatesql.=",VPDSP_SEQ_MAX_JITTER='".$values['VPDSP_SEQ_MAX_JITTER']."'";
endif; 
if($values['VPDSP_JB_MODE'] == '0'):
  $values['VPDSP_MIN_JITTER'] = $_POST['jitter_buffer'] ;
  $updatesql.=",VPDSP_MIN_JITTER='".$values['VPDSP_MIN_JITTER']."'";
endif; 
  $values['RTP_QOS'] = $_POST['rtp_qos'] ;
  $updatesql.=",RTP_QOS='".$values['RTP_QOS']."'";
if($values['RTP_QOS'] == 'IPTOS'):
  $values['RTP_TOS'] = $_POST['rtp_tos'] ;
  $updatesql.=",RTP_TOS='".$values['RTP_TOS']."'";
endif; 
if($values['RTP_QOS'] == 'DIFFSERV'):
  $values['RTP_DIFFSERV'] = $_POST['rtp_diffserv_class'] ;
  $updatesql.=",RTP_DIFFSERV='".$values['RTP_DIFFSERV']."'";
endif; 

  $values['SYMMETRIC_RTP'] = $_POST['symmetric_rtp']=='on'?'1':'0';
  $updatesql.=",SYMMETRIC_RTP='".$values['SYMMETRIC_RTP']."'";
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['MG_NAT_TRAVERSAL'] = $_POST['rtp_nat_traversal'] ;
  $updatesql.=",MG_NAT_TRAVERSAL='".$values['MG_NAT_TRAVERSAL']."'";
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
endif; 
if($values['MG_NAT_TRAVERSAL'] == 'STUN'):
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['MG_STUN_SERVER'] = $_POST['rtp_stun_server'] ;
  $updatesql.=",MG_STUN_SERVER='".$values['MG_STUN_SERVER']."'";
endif; 
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
endif; 
if($values['MG_NAT_TRAVERSAL'] == 'PORTFWD'):
  $values['MG_PORTFWD_TYPE'] = $_POST['rtp_portfwd_type'] ;
  $updatesql.=",MG_PORTFWD_TYPE='".$values['MG_PORTFWD_TYPE']."'";
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
endif; 
if($values['MG_PORTFWD_TYPE'] == 'MANUAL'):
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['MG_PORTFWD_GW'] = $_POST['rtp_portfwd_gw'] ;
  $updatesql.=",MG_PORTFWD_GW='".$values['MG_PORTFWD_GW']."'";
endif; 
endif; 
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
endif; 
if($values['MG_NAT_TRAVERSAL'] == 'RELAY'):
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['MG_RELAY_SERVER'] = $_POST['rtp_relay_server'] ;
  $updatesql.=",MG_RELAY_SERVER='".$values['MG_RELAY_SERVER']."'";
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['MG_RELAY_PORT'] = $_POST['rtp_relay_port'] ;
  $updatesql.=",MG_RELAY_PORT='".$values['MG_RELAY_PORT']."'";
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['MG_RELAY_USER'] = $_POST['rtp_relay_user'] ;
  $updatesql.=",MG_RELAY_USER='".$values['MG_RELAY_USER']."'";
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['MG_RELAY_PASSWD'] = $_POST['rtp_relay_passwd'] ;
  $updatesql.=",MG_RELAY_PASSWD='".$values['MG_RELAY_PASSWD']."'";
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['MG_RELAY_ENCRYPT'] = $_POST['rtp_relay_encrypt']=='on'?'1':'0';
  $updatesql.=",MG_RELAY_ENCRYPT='".$values['MG_RELAY_ENCRYPT']."'";
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['MG_RELAY_MODE'] = $_POST['rtp_relay_mode'] ;
  $updatesql.=",MG_RELAY_MODE='".$values['MG_RELAY_MODE']."'";
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['MG_RELAY_SERVER1'] = $_POST['rtp_relay_server1'] ;
  $updatesql.=",MG_RELAY_SERVER1='".$values['MG_RELAY_SERVER1']."'";
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['MG_RELAY_SERVER2'] = $_POST['rtp_relay_server2'] ;
  $updatesql.=",MG_RELAY_SERVER2='".$values['MG_RELAY_SERVER2']."'";
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['MG_RELAY_SERVER3'] = $_POST['rtp_relay_server3'] ;
  $updatesql.=",MG_RELAY_SERVER3='".$values['MG_RELAY_SERVER3']."'";
endif; 
if($SUPER_USER == '' || $_SESSION['autocfg_adminname'] == $SUPER_USER):
  $values['MG_RELAY_SERVER4'] = $_POST['rtp_relay_server4'] ;
  $updatesql.=",MG_RELAY_SERVER4='".$values['MG_RELAY_SERVER4']."'";
endif; 
endif; 
if($values['SIDE_TONE'] == '1'):
  $values['VPDSP_SIDE_TONE'] = $_POST['side_tone_level'] ;
  $updatesql.=",VPDSP_SIDE_TONE='".$values['VPDSP_SIDE_TONE']."'";
endif; 
/*autocfg srv*/
  $values['AUTOCFG'] = $_POST['auto_config']=='on'?'1':'0';
  $updatesql.=",AUTOCFG='".$values['AUTOCFG']."'";
if($values['AUTOCFG'] == 1):
  $values['AUTOCFG_SERVER'] = $_POST['auto_config_server'] ;
  $updatesql.=",AUTOCFG_SERVER='".$values['AUTOCFG_SERVER']."'";
  $values['AUTOCFG_REFRESH'] = $_POST['auto_config_refresh'] ;
  $updatesql.=",AUTOCFG_REFRESH='".$values['AUTOCFG_REFRESH']."'";
endif;  



  $values['DIAL_PALN'] = $_POST['dial_plan'] ;
  $updatesql.=",DIAL_PALN='".$values['DIAL_PALN']."'";
  
  $values['RADMIN_ENABLE'] = $_POST['remote_enable']=='on'?'1':'0';
  $updatesql.=",RADMIN_ENABLE='".$values['RADMIN_ENABLE']."'";
  $values['RADMIN_SERVER'] = $_POST['remote_server'] ;
  $updatesql.=",RADMIN_SERVER='".$values['RADMIN_SERVER']."'";
  $values['RADMIN_PORT'] = $_POST['remote_server_port'] ;
  $updatesql.=",RADMIN_PORT='".$values['RADMIN_PORT']."'";
  $values['RADMIN_ID'] = $_POST['remote_server_id'] ;
  $updatesql.=",RADMIN_ID='".$values['RADMIN_ID']."'";
  $values['RADMIN_KEY'] = $_POST['remote_server_key'] ;
  $updatesql.=",RADMIN_KEY='".$values['RADMIN_KEY']."'";


/*autoanswer*/
  $values['L1_AUTO_ANSWER_NUM_1'] = $_POST['l1_auto_answer_num1'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_1='".$values['L1_AUTO_ANSWER_NUM_1']."'";
  $values['L1_AUTO_ANSWER_NUM_2'] = $_POST['l1_auto_answer_num2'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_2='".$values['L1_AUTO_ANSWER_NUM_2']."'";
  $values['L1_AUTO_ANSWER_NUM_3'] = $_POST['l1_auto_answer_num3'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_3='".$values['L1_AUTO_ANSWER_NUM_3']."'";
  $values['L1_AUTO_ANSWER_NUM_4'] = $_POST['l1_auto_answer_num4'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_4='".$values['L1_AUTO_ANSWER_NUM_4']."'";
  $values['L1_AUTO_ANSWER_NUM_5'] = $_POST['l1_auto_answer_num5'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_5='".$values['L1_AUTO_ANSWER_NUM_5']."'";
  $values['L1_AUTO_ANSWER_NUM_6'] = $_POST['l1_auto_answer_num6'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_6='".$values['L1_AUTO_ANSWER_NUM_6']."'";
  $values['L1_AUTO_ANSWER_NUM_7'] = $_POST['l1_auto_answer_num7'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_7='".$values['L1_AUTO_ANSWER_NUM_7']."'";
  $values['L1_AUTO_ANSWER_NUM_8'] = $_POST['l1_auto_answer_num8'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_8='".$values['L1_AUTO_ANSWER_NUM_8']."'";
  $values['L1_AUTO_ANSWER_NUM_9'] = $_POST['l1_auto_answer_num9'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_9='".$values['L1_AUTO_ANSWER_NUM_9']."'";
  $values['L1_AUTO_ANSWER_NUM_10'] = $_POST['l1_auto_answer_num10'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_10='".$values['L1_AUTO_ANSWER_NUM_10']."'";
  $values['L1_AUTO_ANSWER_NUM_11'] = $_POST['l1_auto_answer_num11'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_11='".$values['L1_AUTO_ANSWER_NUM_11']."'";
  $values['L1_AUTO_ANSWER_NUM_12'] = $_POST['l1_auto_answer_num12'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_12='".$values['L1_AUTO_ANSWER_NUM_12']."'";
  $values['L1_AUTO_ANSWER_NUM_13'] = $_POST['l1_auto_answer_num13'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_13='".$values['L1_AUTO_ANSWER_NUM_13']."'";
  $values['L1_AUTO_ANSWER_NUM_14'] = $_POST['l1_auto_answer_num14'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_14='".$values['L1_AUTO_ANSWER_NUM_14']."'";
  $values['L1_AUTO_ANSWER_NUM_15'] = $_POST['l1_auto_answer_num15'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_15='".$values['L1_AUTO_ANSWER_NUM_15']."'";
  $values['L1_AUTO_ANSWER_NUM_16'] = $_POST['l1_auto_answer_num16'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_16='".$values['L1_AUTO_ANSWER_NUM_16']."'";
  $values['L1_AUTO_ANSWER_NUM_17'] = $_POST['l1_auto_answer_num17'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_17='".$values['L1_AUTO_ANSWER_NUM_17']."'";
  $values['L1_AUTO_ANSWER_NUM_18'] = $_POST['l1_auto_answer_num18'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_18='".$values['L1_AUTO_ANSWER_NUM_18']."'";
  $values['L1_AUTO_ANSWER_NUM_19'] = $_POST['l1_auto_answer_num19'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_19='".$values['L1_AUTO_ANSWER_NUM_19']."'";
  $values['L1_AUTO_ANSWER_NUM_20'] = $_POST['l1_auto_answer_num20'] ;
  $updatesql.=",L1_AUTO_ANSWER_NUM_20='".$values['L1_AUTO_ANSWER_NUM_20']."'";
  
  $values['L2_AUTO_ANSWER_NUM_1'] = $_POST['l2_auto_answer_num1'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_1='".$values['L2_AUTO_ANSWER_NUM_1']."'";
  $values['L2_AUTO_ANSWER_NUM_2'] = $_POST['l2_auto_answer_num2'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_2='".$values['L2_AUTO_ANSWER_NUM_2']."'";
  $values['L2_AUTO_ANSWER_NUM_3'] = $_POST['l2_auto_answer_num3'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_3='".$values['L2_AUTO_ANSWER_NUM_3']."'";
  $values['L2_AUTO_ANSWER_NUM_4'] = $_POST['l2_auto_answer_num4'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_4='".$values['L2_AUTO_ANSWER_NUM_4']."'";
  $values['L2_AUTO_ANSWER_NUM_5'] = $_POST['l2_auto_answer_num5'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_5='".$values['L2_AUTO_ANSWER_NUM_5']."'";
  $values['L2_AUTO_ANSWER_NUM_6'] = $_POST['l2_auto_answer_num6'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_6='".$values['L2_AUTO_ANSWER_NUM_6']."'";
  $values['L2_AUTO_ANSWER_NUM_7'] = $_POST['l2_auto_answer_num7'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_7='".$values['L2_AUTO_ANSWER_NUM_7']."'";
  $values['L2_AUTO_ANSWER_NUM_8'] = $_POST['l2_auto_answer_num8'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_8='".$values['L2_AUTO_ANSWER_NUM_8']."'";
  $values['L2_AUTO_ANSWER_NUM_9'] = $_POST['l2_auto_answer_num9'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_9='".$values['L2_AUTO_ANSWER_NUM_9']."'";
  $values['L2_AUTO_ANSWER_NUM_10'] = $_POST['l2_auto_answer_num10'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_10='".$values['L2_AUTO_ANSWER_NUM_10']."'";
  $values['L2_AUTO_ANSWER_NUM_11'] = $_POST['l2_auto_answer_num11'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_11='".$values['L2_AUTO_ANSWER_NUM_11']."'";
  $values['L2_AUTO_ANSWER_NUM_12'] = $_POST['l2_auto_answer_num12'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_12='".$values['L2_AUTO_ANSWER_NUM_12']."'";
  $values['L2_AUTO_ANSWER_NUM_13'] = $_POST['l2_auto_answer_num13'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_13='".$values['L2_AUTO_ANSWER_NUM_13']."'";
  $values['L2_AUTO_ANSWER_NUM_14'] = $_POST['l2_auto_answer_num14'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_14='".$values['L2_AUTO_ANSWER_NUM_14']."'";
  $values['L2_AUTO_ANSWER_NUM_15'] = $_POST['l2_auto_answer_num15'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_15='".$values['L2_AUTO_ANSWER_NUM_15']."'";
  $values['L2_AUTO_ANSWER_NUM_16'] = $_POST['l2_auto_answer_num16'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_16='".$values['L2_AUTO_ANSWER_NUM_16']."'";
  $values['L2_AUTO_ANSWER_NUM_17'] = $_POST['l2_auto_answer_num17'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_17='".$values['L2_AUTO_ANSWER_NUM_17']."'";
  $values['L2_AUTO_ANSWER_NUM_18'] = $_POST['l2_auto_answer_num18'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_18='".$values['L2_AUTO_ANSWER_NUM_18']."'";
  $values['L2_AUTO_ANSWER_NUM_19'] = $_POST['l2_auto_answer_num19'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_19='".$values['L2_AUTO_ANSWER_NUM_19']."'";
  $values['L2_AUTO_ANSWER_NUM_20'] = $_POST['l2_auto_answer_num20'] ;
  $updatesql.=",L2_AUTO_ANSWER_NUM_20='".$values['L2_AUTO_ANSWER_NUM_20']."'";
  
  $values['L3_AUTO_ANSWER_NUM_1'] = $_POST['l3_auto_answer_num1'] ;
  $updatesql.=",L3_AUTO_ANSWER_NUM_1='".$values['L3_AUTO_ANSWER_NUM_1']."'";
  $values['L3_AUTO_ANSWER_NUM_2'] = $_POST['l3_auto_answer_num2'] ;
  $updatesql.=",L3_AUTO_ANSWER_NUM_2='".$values['L3_AUTO_ANSWER_NUM_2']."'";
  $values['L3_AUTO_ANSWER_NUM_3'] = $_POST['l3_auto_answer_num3'] ;
  $updatesql.=",L3_AUTO_ANSWER_NUM_3='".$values['L3_AUTO_ANSWER_NUM_3']."'";
  $values['L3_AUTO_ANSWER_NUM_4'] = $_POST['l3_auto_answer_num4'] ;
  $updatesql.=",L3_AUTO_ANSWER_NUM_4='".$values['L3_AUTO_ANSWER_NUM_4']."'";
  $values['L3_AUTO_ANSWER_NUM_5'] = $_POST['l3_auto_answer_num5'] ;
  $updatesql.=",L3_AUTO_ANSWER_NUM_5='".$values['L3_AUTO_ANSWER_NUM_5']."'";
  $values['L3_AUTO_ANSWER_NUM_6'] = $_POST['l3_auto_answer_num6'] ;
  $updatesql.=",L3_AUTO_ANSWER_NUM_6='".$values['L3_AUTO_ANSWER_NUM_6']."'";
  $values['L3_AUTO_ANSWER_NUM_7'] = $_POST['l3_auto_answer_num7'] ;
  $updatesql.=",L3_AUTO_ANSWER_NUM_7='".$values['L3_AUTO_ANSWER_NUM_7']."'";
  $values['L3_AUTO_ANSWER_NUM_8'] = $_POST['l3_auto_answer_num8'] ;
  $updatesql.=",L3_AUTO_ANSWER_NUM_8='".$values['L3_AUTO_ANSWER_NUM_8']."'";
  $values['L3_AUTO_ANSWER_NUM_9'] = $_POST['l3_auto_answer_num9'] ;
  $updatesql.=",L3_AUTO_ANSWER_NUM_9='".$values['L3_AUTO_ANSWER_NUM_9']."'";
  $values['L3_AUTO_ANSWER_NUM_10'] = $_POST['l3_auto_answer_num10'] ;
  $updatesql.=",L3_AUTO_ANSWER_NUM_10='".$values['L3_AUTO_ANSWER_NUM_10']."'";
  $values['L3_AUTO_ANSWER_NUM_11'] = $_POST['l3_auto_answer_num11'] ;
  $updatesql.=",L3_AUTO_ANSWER_NUM_11='".$values['L3_AUTO_ANSWER_NUM_11']."'";
  $values['L3_AUTO_ANSWER_NUM_12'] = $_POST['l3_auto_answer_num12'] ;
  $updatesql.=",L3_AUTO_ANSWER_NUM_12='".$values['L3_AUTO_ANSWER_NUM_12']."'";
  $values['L3_AUTO_ANSWER_NUM_13'] = $_POST['l3_auto_answer_num13'] ;
  $updatesql.=",L3_AUTO_ANSWER_NUM_13='".$values['L3_AUTO_ANSWER_NUM_13']."'";
  $values['L3_AUTO_ANSWER_NUM_14'] = $_POST['l3_auto_answer_num14'] ;
  $updatesql.=",L3_AUTO_ANSWER_NUM_14='".$values['L3_AUTO_ANSWER_NUM_14']."'";
  $values['L3_AUTO_ANSWER_NUM_15'] = $_POST['l3_auto_answer_num15'] ;
  $updatesql.=",L3_AUTO_ANSWER_NUM_15='".$values['L3_AUTO_ANSWER_NUM_15']."'";
  $values['L3_AUTO_ANSWER_NUM_16'] = $_POST['l3_auto_answer_num16'] ;
  $updatesql.=",L3_AUTO_ANSWER_NUM_16='".$values['L3_AUTO_ANSWER_NUM_16']."'";
  $values['L3_AUTO_ANSWER_NUM_17'] = $_POST['l3_auto_answer_num17'] ;
  $updatesql.=",L3_AUTO_ANSWER_NUM_17='".$values['L3_AUTO_ANSWER_NUM_17']."'";
  $values['L3_AUTO_ANSWER_NUM_18'] = $_POST['l3_auto_answer_num18'] ;
  $updatesql.=",L3_AUTO_ANSWER_NUM_18='".$values['L3_AUTO_ANSWER_NUM_18']."'";
  $values['L3_AUTO_ANSWER_NUM_19'] = $_POST['l3_auto_answer_num19'] ;
  $updatesql.=",L3_AUTO_ANSWER_NUM_19='".$values['L3_AUTO_ANSWER_NUM_19']."'";
  $values['L3_AUTO_ANSWER_NUM_20'] = $_POST['l3_auto_answer_num20'] ;
  $updatesql.=",L3_AUTO_ANSWER_NUM_20='".$values['L3_AUTO_ANSWER_NUM_20']."'";

  $values['L4_AUTO_ANSWER_NUM_1'] = $_POST['l4_auto_answer_num1'] ;
  $updatesql.=",L4_AUTO_ANSWER_NUM_1='".$values['L4_AUTO_ANSWER_NUM_1']."'";
  $values['L4_AUTO_ANSWER_NUM_2'] = $_POST['l4_auto_answer_num2'] ;
  $updatesql.=",L4_AUTO_ANSWER_NUM_2='".$values['L4_AUTO_ANSWER_NUM_2']."'";
  $values['L4_AUTO_ANSWER_NUM_3'] = $_POST['l4_auto_answer_num3'] ;
  $updatesql.=",L4_AUTO_ANSWER_NUM_3='".$values['L4_AUTO_ANSWER_NUM_3']."'";
  $values['L4_AUTO_ANSWER_NUM_4'] = $_POST['l4_auto_answer_num4'] ;
  $updatesql.=",L4_AUTO_ANSWER_NUM_4='".$values['L4_AUTO_ANSWER_NUM_4']."'";
  $values['L4_AUTO_ANSWER_NUM_5'] = $_POST['l4_auto_answer_num5'] ;
  $updatesql.=",L4_AUTO_ANSWER_NUM_5='".$values['L4_AUTO_ANSWER_NUM_5']."'";
  $values['L4_AUTO_ANSWER_NUM_6'] = $_POST['l4_auto_answer_num6'] ;
  $updatesql.=",L4_AUTO_ANSWER_NUM_6='".$values['L4_AUTO_ANSWER_NUM_6']."'";
  $values['L4_AUTO_ANSWER_NUM_7'] = $_POST['l4_auto_answer_num7'] ;
  $updatesql.=",L4_AUTO_ANSWER_NUM_7='".$values['L4_AUTO_ANSWER_NUM_7']."'";
  $values['L4_AUTO_ANSWER_NUM_8'] = $_POST['l4_auto_answer_num8'] ;
  $updatesql.=",L4_AUTO_ANSWER_NUM_8='".$values['L4_AUTO_ANSWER_NUM_8']."'";
  $values['L4_AUTO_ANSWER_NUM_9'] = $_POST['l4_auto_answer_num9'] ;
  $updatesql.=",L4_AUTO_ANSWER_NUM_9='".$values['L4_AUTO_ANSWER_NUM_9']."'";
  $values['L4_AUTO_ANSWER_NUM_10'] = $_POST['l4_auto_answer_num10'] ;
  $updatesql.=",L4_AUTO_ANSWER_NUM_10='".$values['L4_AUTO_ANSWER_NUM_10']."'";
  $values['L4_AUTO_ANSWER_NUM_11'] = $_POST['l4_auto_answer_num11'] ;
  $updatesql.=",L4_AUTO_ANSWER_NUM_11='".$values['L4_AUTO_ANSWER_NUM_11']."'";
  $values['L4_AUTO_ANSWER_NUM_12'] = $_POST['l4_auto_answer_num12'] ;
  $updatesql.=",L4_AUTO_ANSWER_NUM_12='".$values['L4_AUTO_ANSWER_NUM_12']."'";
  $values['L4_AUTO_ANSWER_NUM_13'] = $_POST['l4_auto_answer_num13'] ;
  $updatesql.=",L4_AUTO_ANSWER_NUM_13='".$values['L4_AUTO_ANSWER_NUM_13']."'";
  $values['L4_AUTO_ANSWER_NUM_14'] = $_POST['l4_auto_answer_num14'] ;
  $updatesql.=",L4_AUTO_ANSWER_NUM_14='".$values['L4_AUTO_ANSWER_NUM_14']."'";
  $values['L4_AUTO_ANSWER_NUM_15'] = $_POST['l4_auto_answer_num15'] ;
  $updatesql.=",L4_AUTO_ANSWER_NUM_15='".$values['L4_AUTO_ANSWER_NUM_15']."'";
  $values['L4_AUTO_ANSWER_NUM_16'] = $_POST['l4_auto_answer_num16'] ;
  $updatesql.=",L4_AUTO_ANSWER_NUM_16='".$values['L4_AUTO_ANSWER_NUM_16']."'";
  $values['L4_AUTO_ANSWER_NUM_17'] = $_POST['l4_auto_answer_num17'] ;
  $updatesql.=",L4_AUTO_ANSWER_NUM_17='".$values['L4_AUTO_ANSWER_NUM_17']."'";
  $values['L4_AUTO_ANSWER_NUM_18'] = $_POST['l4_auto_answer_num18'] ;
  $updatesql.=",L4_AUTO_ANSWER_NUM_18='".$values['L4_AUTO_ANSWER_NUM_18']."'";
  $values['L4_AUTO_ANSWER_NUM_19'] = $_POST['l4_auto_answer_num19'] ;
  $updatesql.=",L4_AUTO_ANSWER_NUM_19='".$values['L4_AUTO_ANSWER_NUM_19']."'";
  $values['L4_AUTO_ANSWER_NUM_20'] = $_POST['l4_auto_answer_num20'] ;
  $updatesql.=",L4_AUTO_ANSWER_NUM_20='".$values['L4_AUTO_ANSWER_NUM_20']."'";

/*codec*/
  $values['P0_PREFER_CODEC1'] = $_POST['p0_prefer_codec1'] ;
  $updatesql.=",P0_PREFER_CODEC1='".$values['P0_PREFER_CODEC1']."'";
  $values['P0_CODEC1_DISABLE'] = $_POST['p0_codec1_enabled']=='on'?'0':'1';
  $updatesql.=",P0_CODEC1_DISABLE='".$values['P0_CODEC1_DISABLE']."'";
  $values['P0_PREFER_CODEC2'] = $_POST['p0_prefer_codec2'] ;
  $updatesql.=",P0_PREFER_CODEC2='".$values['P0_PREFER_CODEC2']."'";
  $values['P0_CODEC2_DISABLE'] = $_POST['p0_codec2_enabled']=='on'?'0':'1';
  $updatesql.=",P0_CODEC2_DISABLE='".$values['P0_CODEC2_DISABLE']."'";
  $values['P0_PREFER_CODEC3'] = $_POST['p0_prefer_codec3'] ;
  $updatesql.=",P0_PREFER_CODEC3='".$values['P0_PREFER_CODEC3']."'";
  $values['P0_CODEC3_DISABLE'] = $_POST['p0_codec3_enabled']=='on'?'0':'1';
  $updatesql.=",P0_CODEC3_DISABLE='".$values['P0_CODEC3_DISABLE']."'";
  $values['P0_PREFER_CODEC4'] = $_POST['p0_prefer_codec4'] ;
  $updatesql.=",P0_PREFER_CODEC4='".$values['P0_PREFER_CODEC4']."'";
  $values['P0_CODEC4_DISABLE'] = $_POST['p0_codec4_enabled']=='on'?'0':'1';
  $updatesql.=",P0_CODEC4_DISABLE='".$values['P0_CODEC4_DISABLE']."'";
  $values['P0_PREFER_CODEC5'] = $_POST['p0_prefer_codec5'] ;
  $updatesql.=",P0_PREFER_CODEC5='".$values['P0_PREFER_CODEC5']."'";
  $values['P0_CODEC5_DISABLE'] = $_POST['p0_codec5_enabled']=='on'?'0':'1';
  $updatesql.=",P0_CODEC5_DISABLE='".$values['P0_CODEC5_DISABLE']."'";
  $values['P0_PREFER_CODEC6'] = $_POST['p0_prefer_codec6'] ;
  $updatesql.=",P0_PREFER_CODEC6='".$values['P0_PREFER_CODEC6']."'";
  $values['P0_CODEC6_DISABLE'] = $_POST['p0_codec6_enabled']=='on'?'0':'1';
  $updatesql.=",P0_CODEC6_DISABLE='".$values['P0_CODEC6_DISABLE']."'";
  $values['P0_PREFER_CODEC7'] = $_POST['p0_prefer_codec7'] ;
  $updatesql.=",P0_PREFER_CODEC7='".$values['P0_PREFER_CODEC7']."'";
  $values['P0_CODEC7_DISABLE'] = $_POST['p0_codec7_enabled']=='on'?'0':'1';
  $updatesql.=",P0_CODEC7_DISABLE='".$values['P0_CODEC7_DISABLE']."'";

  $values['P2_PREFER_CODEC1'] = $_POST['p2_prefer_codec1'] ;
  $updatesql.=",P2_PREFER_CODEC1='".$values['P2_PREFER_CODEC1']."'";
  $values['P2_CODEC1_DISABLE'] = $_POST['p2_codec1_enabled']=='on'?'0':'1';
  $updatesql.=",P2_CODEC1_DISABLE='".$values['P2_CODEC1_DISABLE']."'";
  $values['P2_PREFER_CODEC2'] = $_POST['p2_prefer_codec2'] ;
  $updatesql.=",P2_PREFER_CODEC2='".$values['P2_PREFER_CODEC2']."'";
  $values['P2_CODEC2_DISABLE'] = $_POST['p2_codec2_enabled']=='on'?'0':'1';
  $updatesql.=",P2_CODEC2_DISABLE='".$values['P2_CODEC2_DISABLE']."'";
  $values['P2_PREFER_CODEC3'] = $_POST['p2_prefer_codec3'] ;
  $updatesql.=",P2_PREFER_CODEC3='".$values['P2_PREFER_CODEC3']."'";
  $values['P2_CODEC3_DISABLE'] = $_POST['p2_codec3_enabled']=='on'?'0':'1';
  $updatesql.=",P2_CODEC3_DISABLE='".$values['P2_CODEC3_DISABLE']."'";
  $values['P2_PREFER_CODEC4'] = $_POST['p2_prefer_codec4'] ;
  $updatesql.=",P2_PREFER_CODEC4='".$values['P2_PREFER_CODEC4']."'";
  $values['P2_CODEC4_DISABLE'] = $_POST['p2_codec4_enabled']=='on'?'0':'1';
  $updatesql.=",P2_CODEC4_DISABLE='".$values['P2_CODEC4_DISABLE']."'";
  $values['P2_PREFER_CODEC5'] = $_POST['p2_prefer_codec5'] ;
  $updatesql.=",P2_PREFER_CODEC5='".$values['P2_PREFER_CODEC5']."'";
  $values['P2_CODEC5_DISABLE'] = $_POST['p2_codec5_enabled']=='on'?'0':'1';
  $updatesql.=",P2_CODEC5_DISABLE='".$values['P2_CODEC5_DISABLE']."'";
  $values['P2_PREFER_CODEC6'] = $_POST['p2_prefer_codec6'] ;
  $updatesql.=",P2_PREFER_CODEC6='".$values['P2_PREFER_CODEC6']."'";
  $values['P2_CODEC6_DISABLE'] = $_POST['p2_codec6_enabled']=='on'?'0':'1';
  $updatesql.=",P2_CODEC6_DISABLE='".$values['P2_CODEC6_DISABLE']."'";
  $values['P2_PREFER_CODEC7'] = $_POST['p2_prefer_codec7'] ;
  $updatesql.=",P2_PREFER_CODEC7='".$values['P2_PREFER_CODEC7']."'";
  $values['P2_CODEC7_DISABLE'] = $_POST['p2_codec7_enabled']=='on'?'0':'1';
  $updatesql.=",P2_CODEC7_DISABLE='".$values['P2_CODEC7_DISABLE']."'";

  $values['P3_PREFER_CODEC1'] = $_POST['p3_prefer_codec1'] ;
  $updatesql.=",P3_PREFER_CODEC1='".$values['P3_PREFER_CODEC1']."'";
  $values['P3_CODEC1_DISABLE'] = $_POST['p3_codec1_enabled']=='on'?'0':'1';
  $updatesql.=",P3_CODEC1_DISABLE='".$values['P3_CODEC1_DISABLE']."'";
  $values['P3_PREFER_CODEC2'] = $_POST['p3_prefer_codec2'] ;
  $updatesql.=",P3_PREFER_CODEC2='".$values['P3_PREFER_CODEC2']."'";
  $values['P3_CODEC2_DISABLE'] = $_POST['p3_codec2_enabled']=='on'?'0':'1';
  $updatesql.=",P3_CODEC2_DISABLE='".$values['P3_CODEC2_DISABLE']."'";
  $values['P3_PREFER_CODEC3'] = $_POST['p3_prefer_codec3'] ;
  $updatesql.=",P3_PREFER_CODEC3='".$values['P3_PREFER_CODEC3']."'";
  $values['P3_CODEC3_DISABLE'] = $_POST['p3_codec3_enabled']=='on'?'0':'1';
  $updatesql.=",P3_CODEC3_DISABLE='".$values['P3_CODEC3_DISABLE']."'";
  $values['P3_PREFER_CODEC4'] = $_POST['p3_prefer_codec4'] ;
  $updatesql.=",P3_PREFER_CODEC4='".$values['P3_PREFER_CODEC4']."'";
  $values['P3_CODEC4_DISABLE'] = $_POST['p3_codec4_enabled']=='on'?'0':'1';
  $updatesql.=",P3_CODEC4_DISABLE='".$values['P3_CODEC4_DISABLE']."'";
  $values['P3_PREFER_CODEC5'] = $_POST['p3_prefer_codec5'] ;
  $updatesql.=",P3_PREFER_CODEC5='".$values['P3_PREFER_CODEC5']."'";
  $values['P3_CODEC5_DISABLE'] = $_POST['p3_codec5_enabled']=='on'?'0':'1';
  $updatesql.=",P3_CODEC5_DISABLE='".$values['P3_CODEC5_DISABLE']."'";
  $values['P3_PREFER_CODEC6'] = $_POST['p3_prefer_codec6'] ;
  $updatesql.=",P3_PREFER_CODEC6='".$values['P3_PREFER_CODEC6']."'";
  $values['P3_CODEC6_DISABLE'] = $_POST['p3_codec6_enabled']=='on'?'0':'1';
  $updatesql.=",P3_CODEC6_DISABLE='".$values['P3_CODEC6_DISABLE']."'";
  $values['P3_PREFER_CODEC7'] = $_POST['p3_prefer_codec7'] ;
  $updatesql.=",P3_PREFER_CODEC7='".$values['P3_PREFER_CODEC7']."'";
  $values['P3_CODEC7_DISABLE'] = $_POST['p3_codec7_enabled']=='on'?'0':'1';
  $updatesql.=",P3_CODEC7_DISABLE='".$values['P3_CODEC7_DISABLE']."'";

  $values['P4_PREFER_CODEC1'] = $_POST['p4_prefer_codec1'] ;
  $updatesql.=",P4_PREFER_CODEC1='".$values['P4_PREFER_CODEC1']."'";
  $values['P4_CODEC1_DISABLE'] = $_POST['p4_codec1_enabled']=='on'?'0':'1';
  $updatesql.=",P4_CODEC1_DISABLE='".$values['P4_CODEC1_DISABLE']."'";
  $values['P4_PREFER_CODEC2'] = $_POST['p4_prefer_codec2'] ;
  $updatesql.=",P4_PREFER_CODEC2='".$values['P4_PREFER_CODEC2']."'";
  $values['P4_CODEC2_DISABLE'] = $_POST['p4_codec2_enabled']=='on'?'0':'1';
  $updatesql.=",P4_CODEC2_DISABLE='".$values['P4_CODEC2_DISABLE']."'";
  $values['P4_PREFER_CODEC3'] = $_POST['p4_prefer_codec3'] ;
  $updatesql.=",P4_PREFER_CODEC3='".$values['P4_PREFER_CODEC3']."'";
  $values['P4_CODEC3_DISABLE'] = $_POST['p4_codec3_enabled']=='on'?'0':'1';
  $updatesql.=",P4_CODEC3_DISABLE='".$values['P4_CODEC3_DISABLE']."'";
  $values['P4_PREFER_CODEC4'] = $_POST['p4_prefer_codec4'] ;
  $updatesql.=",P4_PREFER_CODEC4='".$values['P4_PREFER_CODEC4']."'";
  $values['P4_CODEC4_DISABLE'] = $_POST['p4_codec4_enabled']=='on'?'0':'1';
  $updatesql.=",P4_CODEC4_DISABLE='".$values['P4_CODEC4_DISABLE']."'";
  $values['P4_PREFER_CODEC5'] = $_POST['p4_prefer_codec5'] ;
  $updatesql.=",P4_PREFER_CODEC5='".$values['P4_PREFER_CODEC5']."'";
  $values['P4_CODEC5_DISABLE'] = $_POST['p4_codec5_enabled']=='on'?'0':'1';
  $updatesql.=",P4_CODEC5_DISABLE='".$values['P4_CODEC5_DISABLE']."'";
  $values['P4_PREFER_CODEC6'] = $_POST['p4_prefer_codec6'] ;
  $updatesql.=",P4_PREFER_CODEC6='".$values['P4_PREFER_CODEC6']."'";
  $values['P4_CODEC6_DISABLE'] = $_POST['p4_codec6_enabled']=='on'?'0':'1';
  $updatesql.=",P4_CODEC6_DISABLE='".$values['P4_CODEC6_DISABLE']."'";
  $values['P4_PREFER_CODEC7'] = $_POST['p4_prefer_codec7'] ;
  $updatesql.=",P4_PREFER_CODEC7='".$values['P4_PREFER_CODEC7']."'";
  $values['P4_CODEC7_DISABLE'] = $_POST['p4_codec7_enabled']=='on'?'0':'1';
  $updatesql.=",P4_CODEC7_DISABLE='".$values['P4_CODEC7_DISABLE']."'";

  $values['P5_PREFER_CODEC1'] = $_POST['p5_prefer_codec1'] ;
  $updatesql.=",P5_PREFER_CODEC1='".$values['P5_PREFER_CODEC1']."'";
  $values['P5_CODEC1_DISABLE'] = $_POST['p5_codec1_enabled']=='on'?'0':'1';
  $updatesql.=",P5_CODEC1_DISABLE='".$values['P5_CODEC1_DISABLE']."'";
  $values['P5_PREFER_CODEC2'] = $_POST['p5_prefer_codec2'] ;
  $updatesql.=",P5_PREFER_CODEC2='".$values['P5_PREFER_CODEC2']."'";
  $values['P5_CODEC2_DISABLE'] = $_POST['p5_codec2_enabled']=='on'?'0':'1';
  $updatesql.=",P5_CODEC2_DISABLE='".$values['P5_CODEC2_DISABLE']."'";
  $values['P5_PREFER_CODEC3'] = $_POST['p5_prefer_codec3'] ;
  $updatesql.=",P5_PREFER_CODEC3='".$values['P5_PREFER_CODEC3']."'";
  $values['P5_CODEC3_DISABLE'] = $_POST['p5_codec3_enabled']=='on'?'0':'1';
  $updatesql.=",P5_CODEC3_DISABLE='".$values['P5_CODEC3_DISABLE']."'";
  $values['P5_PREFER_CODEC4'] = $_POST['p5_prefer_codec4'] ;
  $updatesql.=",P5_PREFER_CODEC4='".$values['P5_PREFER_CODEC4']."'";
  $values['P5_CODEC4_DISABLE'] = $_POST['p5_codec4_enabled']=='on'?'0':'1';
  $updatesql.=",P5_CODEC4_DISABLE='".$values['P5_CODEC4_DISABLE']."'";
  $values['P5_PREFER_CODEC5'] = $_POST['p5_prefer_codec5'] ;
  $updatesql.=",P5_PREFER_CODEC5='".$values['P5_PREFER_CODEC5']."'";
  $values['P5_CODEC5_DISABLE'] = $_POST['p5_codec5_enabled']=='on'?'0':'1';
  $updatesql.=",P5_CODEC5_DISABLE='".$values['P5_CODEC5_DISABLE']."'";
  $values['P5_PREFER_CODEC6'] = $_POST['p5_prefer_codec6'] ;
  $updatesql.=",P5_PREFER_CODEC6='".$values['P5_PREFER_CODEC6']."'";
  $values['P5_CODEC6_DISABLE'] = $_POST['p5_codec6_enabled']=='on'?'0':'1';
  $updatesql.=",P5_CODEC6_DISABLE='".$values['P5_CODEC6_DISABLE']."'";
  $values['P5_PREFER_CODEC7'] = $_POST['p5_prefer_codec7'] ;
  $updatesql.=",P5_PREFER_CODEC7='".$values['P5_PREFER_CODEC7']."'";
  $values['P5_CODEC7_DISABLE'] = $_POST['p5_codec7_enabled']=='on'?'0':'1';
  $updatesql.=",P5_CODEC7_DISABLE='".$values['P5_CODEC7_DISABLE']."'";
  
  
  $insertsql.=",SIP_WORK_MODE";
  $insertsql2.="','".$values['SIP_WORK_MODE'];
  $insertsql.=",SIP_CONTACT0_DIAL_DIGITS";
  $insertsql2.="','".$values['SIP_CONTACT0_DIAL_DIGITS'];
  $insertsql.=",SIP_CONTACT0_LOGIN";
  $insertsql2.="','".$values['SIP_CONTACT0_LOGIN'];
  $insertsql.=",SIP_CONTACT0_PASSWD";
  $insertsql2.="','".$values['SIP_CONTACT0_PASSWD'];
  $insertsql.=",SIP_CONTACT0_DISPLAY_NAME";
  $insertsql2.="','".$values['SIP_CONTACT0_DISPLAY_NAME'];
  $insertsql.=",C1_RING_TYPE";
  $insertsql2.="','".$values['C1_RING_TYPE'];
  $insertsql.=",SIP_CONTACT0_DIAL_DIGITS_2";
  $insertsql2.="','".$values['SIP_CONTACT0_DIAL_DIGITS_2'];
  $insertsql.=",SIP_CONTACT0_LOGIN_2";
  $insertsql2.="','".$values['SIP_CONTACT0_LOGIN_2'];
  $insertsql.=",SIP_CONTACT0_PASSWD_2";
  $insertsql2.="','".$values['SIP_CONTACT0_PASSWD_2'];
  $insertsql.=",SIP_CONTACT0_DISPLAY_NAME_2";
  $insertsql2.="','".$values['SIP_CONTACT0_DISPLAY_NAME_2'];
  $insertsql.=",C2_RING_TYPE";
  $insertsql2.="','".$values['C2_RING_TYPE'];
  $insertsql.=",SIP_CONTACT0_DIAL_DIGITS_3";
  $insertsql2.="','".$values['SIP_CONTACT0_DIAL_DIGITS_3'];
  $insertsql.=",SIP_CONTACT0_LOGIN_3";
  $insertsql2.="','".$values['SIP_CONTACT0_LOGIN_3'];
  $insertsql.=",SIP_CONTACT0_PASSWD_3";
  $insertsql2.="','".$values['SIP_CONTACT0_PASSWD_3'];
  $insertsql.=",SIP_CONTACT0_DISPLAY_NAME_3";
  $insertsql2.="','".$values['SIP_CONTACT0_DISPLAY_NAME_3'];
  $insertsql.=",C3_RING_TYPE";
  $insertsql2.="','".$values['C3_RING_TYPE'];
  $insertsql.=",SIP_CONTACT0_DIAL_DIGITS_4";
  $insertsql2.="','".$values['SIP_CONTACT0_DIAL_DIGITS_4'];
  $insertsql.=",SIP_CONTACT0_LOGIN_4";
  $insertsql2.="','".$values['SIP_CONTACT0_LOGIN_4'];
  $insertsql.=",SIP_CONTACT0_PASSWD_4";
  $insertsql2.="','".$values['SIP_CONTACT0_PASSWD_4'];
  $insertsql.=",SIP_CONTACT0_DISPLAY_NAME_4";
  $insertsql2.="','".$values['SIP_CONTACT0_DISPLAY_NAME_4'];
  $insertsql.=",C4_RING_TYPE";
  $insertsql2.="','".$values['C4_RING_TYPE'];
  $insertsql.=",SIP_CONTACT0_PROXY";
  $insertsql2.="','".$values['SIP_CONTACT0_PROXY'];
  $insertsql.=",SIP_CONTACT0_SERVER";
  $insertsql2.="','".$values['SIP_CONTACT0_SERVER'];
  $insertsql.=",SIP_CONTACT0_EXPIRED";
  $insertsql2.="','".$values['SIP_CONTACT0_EXPIRED'];
  $insertsql.=",SIP_CONTACT0_OUTBOUND_PROXY";
  $insertsql2.="','".$values['SIP_CONTACT0_OUTBOUND_PROXY'];
  $insertsql.=",SIP_CONTACT0_HOME_DOMAIN";
  $insertsql2.="','".$values['SIP_CONTACT0_HOME_DOMAIN'];
  $insertsql.=",SIP_CONTACT0_CALL_WAIT";
  $insertsql2.="','".$values['SIP_CONTACT0_CALL_WAIT'];
  $insertsql.=",SIP_CONTACT0_FORWARD_TYPE";
  $insertsql2.="','".$values['SIP_CONTACT0_FORWARD_TYPE'];
  $insertsql.=",SIP_CONTACT0_FORWARD_NUMBER";
  $insertsql2.="','".$values['SIP_CONTACT0_FORWARD_NUMBER'];
  $insertsql.=",SIP_CONTACT0_VM_NUM";
  $insertsql2.="','".$values['SIP_CONTACT0_VM_NUM'];
  $insertsql.=",P0_HOT_LINE_NUM";
  $insertsql2.="','".$values['P0_HOT_LINE_NUM'];
  $insertsql.=",P0_DIAL_PLAN";
  $insertsql2.="','".$values['P0_DIAL_PLAN'];
  $insertsql.=",USE_BACKUP_SIP_SVR";
  $insertsql2.="','".$values['USE_BACKUP_SIP_SVR'];
  $insertsql.=",SIP_CONTACT1_PROXY";
  $insertsql2.="','".$values['SIP_CONTACT1_PROXY'];
  $insertsql.=",SIP_CONTACT1_SERVER";
  $insertsql2.="','".$values['SIP_CONTACT1_SERVER'];
  $insertsql.=",SIP_CONTACT1_OUTBOUND_PROXY";
  $insertsql2.="','".$values['SIP_CONTACT1_OUTBOUND_PROXY'];
  $insertsql.=",SIP_CONTACT1_HOME_DOMAIN";
  $insertsql2.="','".$values['SIP_CONTACT1_HOME_DOMAIN'];
  $insertsql.=",SIP_CONTACT2_DIAL_DIGITS";
  $insertsql2.="','".$values['SIP_CONTACT2_DIAL_DIGITS'];
  $insertsql.=",SIP_CONTACT2_DISPLAY_NAME";
  $insertsql2.="','".$values['SIP_CONTACT2_DISPLAY_NAME'];
  $insertsql.=",SIP_CONTACT2_PROXY";
  $insertsql2.="','".$values['SIP_CONTACT2_PROXY'];
  $insertsql.=",SIP_CONTACT2_SERVER";
  $insertsql2.="','".$values['SIP_CONTACT2_SERVER'];
  $insertsql.=",SIP_CONTACT2_EXPIRED";
  $insertsql2.="','".$values['SIP_CONTACT2_EXPIRED'];
  $insertsql.=",SIP_CONTACT2_OUTBOUND_PROXY";
  $insertsql2.="','".$values['SIP_CONTACT2_OUTBOUND_PROXY'];
  $insertsql.=",SIP_CONTACT2_HOME_DOMAIN";
  $insertsql2.="','".$values['SIP_CONTACT2_HOME_DOMAIN'];
  $insertsql.=",SIP_CONTACT2_LOGIN";
  $insertsql2.="','".$values['SIP_CONTACT2_LOGIN'];
  $insertsql.=",SIP_CONTACT2_PASSWD";
  $insertsql2.="','".$values['SIP_CONTACT2_PASSWD'];
  $insertsql.=",SIP_CONTACT2_CALL_WAIT";
  $insertsql2.="','".$values['SIP_CONTACT2_CALL_WAIT'];
  $insertsql.=",SIP_CONTACT2_FORWARD_TYPE";
  $insertsql2.="','".$values['SIP_CONTACT2_FORWARD_TYPE'];
  $insertsql.=",SIP_CONTACT2_FORWARD_NUMBER";
  $insertsql2.="','".$values['SIP_CONTACT2_FORWARD_NUMBER'];
  $insertsql.=",SIP_CONTACT2_VM_NUM";
  $insertsql2.="','".$values['SIP_CONTACT2_VM_NUM'];
  $insertsql.=",P1_HOT_LINE_NUM";
  $insertsql2.="','".$values['P1_HOT_LINE_NUM'];
  $insertsql.=",P1_DIAL_PLAN";
  $insertsql2.="','".$values['P1_DIAL_PLAN'];
  $insertsql.=",P1_RING_TYPE";
  $insertsql2.="','".$values['P1_RING_TYPE'];
  $insertsql.=",L1_AUTO_ANSWER";
  $insertsql2.="','".$values['L1_AUTO_ANSWER'];
  $insertsql.=",SIP_CONTACT3_DIAL_DIGITS";
  $insertsql2.="','".$values['SIP_CONTACT3_DIAL_DIGITS'];
  $insertsql.=",SIP_CONTACT3_DISPLAY_NAME";
  $insertsql2.="','".$values['SIP_CONTACT3_DISPLAY_NAME'];
  $insertsql.=",SIP_CONTACT3_PROXY";
  $insertsql2.="','".$values['SIP_CONTACT3_PROXY'];
  $insertsql.=",SIP_CONTACT3_SERVER";
  $insertsql2.="','".$values['SIP_CONTACT3_SERVER'];
  $insertsql.=",SIP_CONTACT3_EXPIRED";
  $insertsql2.="','".$values['SIP_CONTACT3_EXPIRED'];
  $insertsql.=",SIP_CONTACT3_OUTBOUND_PROXY";
  $insertsql2.="','".$values['SIP_CONTACT3_OUTBOUND_PROXY'];
  $insertsql.=",SIP_CONTACT3_HOME_DOMAIN";
  $insertsql2.="','".$values['SIP_CONTACT3_HOME_DOMAIN'];
  $insertsql.=",SIP_CONTACT3_LOGIN";
  $insertsql2.="','".$values['SIP_CONTACT3_LOGIN'];
  $insertsql.=",SIP_CONTACT3_PASSWD";
  $insertsql2.="','".$values['SIP_CONTACT3_PASSWD'];
  $insertsql.=",SIP_CONTACT3_CALL_WAIT";
  $insertsql2.="','".$values['SIP_CONTACT3_CALL_WAIT'];
  $insertsql.=",SIP_CONTACT3_FORWARD_TYPE";
  $insertsql2.="','".$values['SIP_CONTACT3_FORWARD_TYPE'];
  $insertsql.=",SIP_CONTACT3_FORWARD_NUMBER";
  $insertsql2.="','".$values['SIP_CONTACT3_FORWARD_NUMBER'];
  $insertsql.=",SIP_CONTACT3_VM_NUM";
  $insertsql2.="','".$values['SIP_CONTACT3_VM_NUM'];
  $insertsql.=",P2_HOT_LINE_NUM";
  $insertsql2.="','".$values['P2_HOT_LINE_NUM'];
  $insertsql.=",P2_DIAL_PLAN";
  $insertsql2.="','".$values['P2_DIAL_PLAN'];
  $insertsql.=",P2_RING_TYPE";
  $insertsql2.="','".$values['P2_RING_TYPE'];
  $insertsql.=",L2_AUTO_ANSWER";
  $insertsql2.="','".$values['L2_AUTO_ANSWER'];
  $insertsql.=",SIP_CONTACT4_DIAL_DIGITS";
  $insertsql2.="','".$values['SIP_CONTACT4_DIAL_DIGITS'];
  $insertsql.=",SIP_CONTACT4_DISPLAY_NAME";
  $insertsql2.="','".$values['SIP_CONTACT4_DISPLAY_NAME'];
  $insertsql.=",SIP_CONTACT4_PROXY";
  $insertsql2.="','".$values['SIP_CONTACT4_PROXY'];
  $insertsql.=",SIP_CONTACT4_SERVER";
  $insertsql2.="','".$values['SIP_CONTACT4_SERVER'];
  $insertsql.=",SIP_CONTACT4_EXPIRED";
  $insertsql2.="','".$values['SIP_CONTACT4_EXPIRED'];
  $insertsql.=",SIP_CONTACT4_OUTBOUND_PROXY";
  $insertsql2.="','".$values['SIP_CONTACT4_OUTBOUND_PROXY'];
  $insertsql.=",SIP_CONTACT4_HOME_DOMAIN";
  $insertsql2.="','".$values['SIP_CONTACT4_HOME_DOMAIN'];
  $insertsql.=",SIP_CONTACT4_LOGIN";
  $insertsql2.="','".$values['SIP_CONTACT4_LOGIN'];
  $insertsql.=",SIP_CONTACT4_PASSWD";
  $insertsql2.="','".$values['SIP_CONTACT4_PASSWD'];
  $insertsql.=",SIP_CONTACT4_CALL_WAIT";
  $insertsql2.="','".$values['SIP_CONTACT4_CALL_WAIT'];
  $insertsql.=",SIP_CONTACT4_FORWARD_TYPE";
  $insertsql2.="','".$values['SIP_CONTACT4_FORWARD_TYPE'];
  $insertsql.=",SIP_CONTACT4_FORWARD_NUMBER";
  $insertsql2.="','".$values['SIP_CONTACT4_FORWARD_NUMBER'];
  $insertsql.=",SIP_CONTACT4_VM_NUM";
  $insertsql2.="','".$values['SIP_CONTACT4_VM_NUM'];
  $insertsql.=",P3_HOT_LINE_NUM";
  $insertsql2.="','".$values['P3_HOT_LINE_NUM'];
  $insertsql.=",P3_DIAL_PLAN";
  $insertsql2.="','".$values['P3_DIAL_PLAN'];
  $insertsql.=",P3_RING_TYPE";
  $insertsql2.="','".$values['P3_RING_TYPE'];
  $insertsql.=",L3_AUTO_ANSWER";
  $insertsql2.="','".$values['L3_AUTO_ANSWER'];
  $insertsql.=",SIP_CONTACT5_DIAL_DIGITS";
  $insertsql2.="','".$values['SIP_CONTACT5_DIAL_DIGITS'];
  $insertsql.=",SIP_CONTACT5_DISPLAY_NAME";
  $insertsql2.="','".$values['SIP_CONTACT5_DISPLAY_NAME'];
  $insertsql.=",SIP_CONTACT5_PROXY";
  $insertsql2.="','".$values['SIP_CONTACT5_PROXY'];
  $insertsql.=",SIP_CONTACT5_SERVER";
  $insertsql2.="','".$values['SIP_CONTACT5_SERVER'];
  $insertsql.=",SIP_CONTACT5_EXPIRED";
  $insertsql2.="','".$values['SIP_CONTACT5_EXPIRED'];
  $insertsql.=",SIP_CONTACT5_OUTBOUND_PROXY";
  $insertsql2.="','".$values['SIP_CONTACT5_OUTBOUND_PROXY'];
  $insertsql.=",SIP_CONTACT5_HOME_DOMAIN";
  $insertsql2.="','".$values['SIP_CONTACT5_HOME_DOMAIN'];
  $insertsql.=",SIP_CONTACT5_LOGIN";
  $insertsql2.="','".$values['SIP_CONTACT5_LOGIN'];
  $insertsql.=",SIP_CONTACT5_PASSWD";
  $insertsql2.="','".$values['SIP_CONTACT5_PASSWD'];
  $insertsql.=",SIP_CONTACT5_CALL_WAIT";
  $insertsql2.="','".$values['SIP_CONTACT5_CALL_WAIT'];
  $insertsql.=",SIP_CONTACT5_FORWARD_TYPE";
  $insertsql2.="','".$values['SIP_CONTACT5_FORWARD_TYPE'];
  $insertsql.=",SIP_CONTACT5_FORWARD_NUMBER";
  $insertsql2.="','".$values['SIP_CONTACT5_FORWARD_NUMBER'];
  $insertsql.=",SIP_CONTACT5_VM_NUM";
  $insertsql2.="','".$values['SIP_CONTACT5_VM_NUM'];
  $insertsql.=",P4_HOT_LINE_NUM";
  $insertsql2.="','".$values['P4_HOT_LINE_NUM'];
  $insertsql.=",P4_DIAL_PLAN";
  $insertsql2.="','".$values['P4_DIAL_PLAN'];
  $insertsql.=",P4_RING_TYPE";
  $insertsql2.="','".$values['P4_RING_TYPE'];
  $insertsql.=",L4_AUTO_ANSWER";
  $insertsql2.="','".$values['L4_AUTO_ANSWER'];
  
/*ad*/
  $insertsql.=",SIP_LOCAL_PORT";
  $insertsql2.="','".$values['SIP_LOCAL_PORT'];
  $insertsql.=",SIP_MWI";
  $insertsql2.="','".$values['SIP_MWI'];
  $insertsql.=",SIP_NO_ALIVE";
  $insertsql2.="','".$values['SIP_NO_ALIVE'];
  $insertsql.=",SIP_P2P_ENABLE";
  $insertsql2.="','".$values['SIP_P2P_ENABLE'];
  $insertsql.=",INBAND_DTMF";
  $insertsql2.="','".$values['INBAND_DTMF'];
  $insertsql.=",SIP_OUTBAND_DTMF_TYPE";
  $insertsql2.="','".$values['SIP_OUTBAND_DTMF_TYPE'];
  $insertsql.=",DTMF_PAYLOAD_TYPE";
  $insertsql2.="','".$values['DTMF_PAYLOAD_TYPE'];
  $insertsql.=",SIP_QOS";
  $insertsql2.="','".$values['SIP_QOS'];
  $insertsql.=",SIP_TOS";
  $insertsql2.="','".$values['SIP_TOS'];
  $insertsql.=",SIP_DIFFSERV";
  $insertsql2.="','".$values['SIP_DIFFSERV'];
  $insertsql.=",SIP_NAT_TRAVERSAL";
  $insertsql2.="','".$values['SIP_NAT_TRAVERSAL'];
  $insertsql.=",SIP_STUN_SERVER";
  $insertsql2.="','".$values['SIP_STUN_SERVER'];
  $insertsql.=",SIP_RELAY_SERVER";
  $insertsql2.="','".$values['SIP_RELAY_SERVER'];
  $insertsql.=",SIP_RELAY_PORT";
  $insertsql2.="','".$values['SIP_RELAY_PORT'];
  $insertsql.=",SIP_RELAY_USER";
  $insertsql2.="','".$values['SIP_RELAY_USER'];
  $insertsql.=",SIP_RELAY_PASSWD";
  $insertsql2.="','".$values['SIP_RELAY_PASSWD'];
  $insertsql.=",SIP_RELAY_ENCRYPT";
  $insertsql2.="','".$values['SIP_RELAY_ENCRYPT'];
  $insertsql.=",SIP_RELAY_SERVER1";
  $insertsql2.="','".$values['SIP_RELAY_SERVER1'];
  $insertsql.=",SIP_RELAY_SERVER2";
  $insertsql2.="','".$values['SIP_RELAY_SERVER2'];
  $insertsql.=",SIP_RELAY_SERVER3";
  $insertsql2.="','".$values['SIP_RELAY_SERVER3'];
  $insertsql.=",SIP_RELAY_SERVER4";
  $insertsql2.="','".$values['SIP_RELAY_SERVER4'];

/*medio*/
  $insertsql.=",RTP_PORT";
  $insertsql2.="','".$values['RTP_PORT'];
  $insertsql.=",PACKETIZE_PERIOD";
  $insertsql2.="','".$values['PACKETIZE_PERIOD'];
  $insertsql.=",VPDSP_JB_MODE";
  $insertsql2.="','".$values['VPDSP_JB_MODE'];
  $insertsql.=",VPDSP_ADPT_MIN_JITTER";
  $insertsql2.="','".$values['VPDSP_ADPT_MIN_JITTER'];
  $insertsql.=",VPDSP_ADPT_MAX_JITTER";
  $insertsql2.="','".$values['VPDSP_ADPT_MAX_JITTER'];
  $insertsql.=",VPDSP_SEQ_MIN_JITTER";
  $insertsql2.="','".$values['VPDSP_SEQ_MIN_JITTER'];
  $insertsql.=",VPDSP_SEQ_MAX_JITTER";
  $insertsql2.="','".$values['VPDSP_SEQ_MAX_JITTER'];
  $insertsql.=",VPDSP_MIN_JITTER";
  $insertsql2.="','".$values['VPDSP_MIN_JITTER'];
  $insertsql.=",RTP_QOS";
  $insertsql2.="','".$values['RTP_QOS'];
  $insertsql.=",RTP_TOS";
  $insertsql2.="','".$values['RTP_TOS'];
  $insertsql.=",RTP_DIFFSERV";
  $insertsql2.="','".$values['RTP_DIFFSERV'];
  $insertsql.=",SYMMETRIC_RTP";
  $insertsql2.="','".$values['SYMMETRIC_RTP'];
  $insertsql.=",MG_NAT_TRAVERSAL";
  $insertsql2.="','".$values['MG_NAT_TRAVERSAL'];
  $insertsql.=",MG_STUN_SERVER";
  $insertsql2.="','".$values['MG_STUN_SERVER'];
  $insertsql.=",MG_PORTFWD_TYPE";
  $insertsql2.="','".$values['MG_PORTFWD_TYPE'];
  $insertsql.=",MG_PORTFWD_GW";
  $insertsql2.="','".$values['MG_PORTFWD_GW'];
  $insertsql.=",MG_RELAY_SERVER";
  $insertsql2.="','".$values['MG_RELAY_SERVER'];
  $insertsql.=",MG_RELAY_PORT";
  $insertsql2.="','".$values['MG_RELAY_PORT'];
  $insertsql.=",MG_RELAY_USER";
  $insertsql2.="','".$values['MG_RELAY_USER'];
  $insertsql.=",MG_RELAY_PASSWD";
  $insertsql2.="','".$values['MG_RELAY_PASSWD'];
  $insertsql.=",MG_RELAY_ENCRYPT";
  $insertsql2.="','".$values['MG_RELAY_ENCRYPT'];
  $insertsql.=",MG_RELAY_MODE";
  $insertsql2.="','".$values['MG_RELAY_MODE'];
  $insertsql.=",MG_RELAY_SERVER1";
  $insertsql2.="','".$values['MG_RELAY_SERVER1'];
  $insertsql.=",MG_RELAY_SERVER2";
  $insertsql2.="','".$values['MG_RELAY_SERVER2'];
  $insertsql.=",MG_RELAY_SERVER3";
  $insertsql2.="','".$values['MG_RELAY_SERVER3'];
  $insertsql.=",MG_RELAY_SERVER4";
  $insertsql2.="','".$values['MG_RELAY_SERVER4'];
  $insertsql.=",VPDSP_SIDE_TONE";
  $insertsql2.="','".$values['VPDSP_SIDE_TONE'];
  $insertsql.=",AUTOCFG";
  $insertsql2.="','".$values['AUTOCFG'];
  $insertsql.=",AUTOCFG_SERVER";
  $insertsql2.="','".$values['AUTOCFG_SERVER'];
  $insertsql.=",AUTOCFG_REFRESH";                                                                                 
  $insertsql2.="','".$values['AUTOCFG_REFRESH'];                                                                  
  $insertsql.=",DIAL_PALN";  
  $insertsql2.="','".$values['DIAL_PALN'];
  $insertsql.=",RADMIN_ENABLE";
  $insertsql2.="','".$values['RADMIN_ENABLE'];
  $insertsql.=",RADMIN_SERVER";
  $insertsql2.="','".$values['RADMIN_SERVER'];
  $insertsql.=",RADMIN_PORT";
  $insertsql2.="','".$values['RADMIN_PORT'];
  $insertsql.=",RADMIN_ID";
  $insertsql2.="','".$values['RADMIN_ID'];
  $insertsql.=",RADMIN_KEY";
  $insertsql2.="','".$values['RADMIN_KEY'];
  
  
  $insertsql.=",SIP_KEEPALIVE_INTERVAL";
  $insertsql2.="','".$values['SIP_KEEPALIVE_INTERVAL'];
  $insertsql.=",SIP_FAIL_RETRY_INTERVAL";
  $insertsql2.="','".$values['SIP_FAIL_RETRY_INTERVAL'];

 //可能没有此参数
  $insertsql.=",SIP_REGISTER_EXPIRY";
  $insertsql2.="','".$values['SIP_REGISTER_EXPIRY'];
  $insertsql.=",SIP_SUBSCRIBE_EXPIRY";
  $insertsql2.="','".$values['SIP_SUBSCRIBE_EXPIRY'];


  $insertsql.=",UNANSWER_FW_EXP";
  $insertsql2.="','".$values['UNANSWER_FW_EXP'];
  $insertsql.=",UNANSWER_EXP";
  $insertsql2.="','".$values['UNANSWER_EXP'];
  $insertsql.=",NON_INVITE_TS_EXP";
  $insertsql2.="','".$values['NON_INVITE_TS_EXP'];
  $insertsql.=",INVITE_TS_EXP";
  $insertsql2.="','".$values['INVITE_TS_EXP'];
  $insertsql.=",RETRANSMIT_T1";
  $insertsql2.="','".$values['RETRANSMIT_T1'];
  $insertsql.=",RETRANSMIT_T2";
  $insertsql2.="','".$values['RETRANSMIT_T2'];
  


/*autoanswer*/
  $insertsql.=",L1_AUTO_ANSWER_NUM_1";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_1'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_2";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_2'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_3";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_3'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_4";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_4'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_5";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_5'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_6";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_6'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_7";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_7'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_8";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_8'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_9";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_9'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_10";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_10'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_11";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_11'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_12";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_12'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_13";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_13'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_14";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_14'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_15";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_15'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_16";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_16'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_17";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_17'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_18";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_18'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_19";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_19'];
  $insertsql.=",L1_AUTO_ANSWER_NUM_20";
  $insertsql2.="','".$values['L1_AUTO_ANSWER_NUM_20'];

  $insertsql.=",L2_AUTO_ANSWER_NUM_1";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_1'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_2";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_2'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_3";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_3'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_4";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_4'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_5";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_5'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_6";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_6'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_7";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_7'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_8";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_8'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_9";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_9'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_10";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_10'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_11";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_11'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_12";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_12'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_13";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_13'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_14";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_14'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_15";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_15'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_16";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_16'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_17";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_17'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_18";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_18'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_19";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_19'];
  $insertsql.=",L2_AUTO_ANSWER_NUM_20";
  $insertsql2.="','".$values['L2_AUTO_ANSWER_NUM_20'];

  $insertsql.=",L3_AUTO_ANSWER_NUM_1";
  $insertsql2.="','".$values['L3_AUTO_ANSWER_NUM_1'];
  $insertsql.=",L3_AUTO_ANSWER_NUM_2";
  $insertsql2.="','".$values['L3_AUTO_ANSWER_NUM_2'];
  $insertsql.=",L3_AUTO_ANSWER_NUM_3";
  $insertsql2.="','".$values['L3_AUTO_ANSWER_NUM_3'];
  $insertsql.=",L3_AUTO_ANSWER_NUM_4";
  $insertsql2.="','".$values['L3_AUTO_ANSWER_NUM_4'];
  $insertsql.=",L3_AUTO_ANSWER_NUM_5";
  $insertsql2.="','".$values['L3_AUTO_ANSWER_NUM_5'];
  $insertsql.=",L3_AUTO_ANSWER_NUM_6";
  $insertsql2.="','".$values['L3_AUTO_ANSWER_NUM_6'];
  $insertsql.=",L3_AUTO_ANSWER_NUM_7";
  $insertsql2.="','".$values['L3_AUTO_ANSWER_NUM_7'];
  $insertsql.=",L3_AUTO_ANSWER_NUM_8";
  $insertsql2.="','".$values['L3_AUTO_ANSWER_NUM_8'];
  $insertsql.=",L3_AUTO_ANSWER_NUM_9";
  $insertsql2.="','".$values['L3_AUTO_ANSWER_NUM_9'];
  $insertsql.=",L3_AUTO_ANSWER_NUM_10";
  $insertsql2.="','".$values['L3_AUTO_ANSWER_NUM_10'];
  $insertsql.=",L3_AUTO_ANSWER_NUM_11";
  $insertsql2.="','".$values['L3_AUTO_ANSWER_NUM_11'];
  $insertsql.=",L3_AUTO_ANSWER_NUM_12";
  $insertsql2.="','".$values['L3_AUTO_ANSWER_NUM_12'];
  $insertsql.=",L3_AUTO_ANSWER_NUM_13";
  $insertsql2.="','".$values['L3_AUTO_ANSWER_NUM_13'];
  $insertsql.=",L3_AUTO_ANSWER_NUM_14";
  $insertsql2.="','".$values['L3_AUTO_ANSWER_NUM_14'];
  $insertsql.=",L3_AUTO_ANSWER_NUM_15";
  $insertsql2.="','".$values['L3_AUTO_ANSWER_NUM_15'];
  $insertsql.=",L3_AUTO_ANSWER_NUM_16";
  $insertsql2.="','".$values['L3_AUTO_ANSWER_NUM_16'];
  $insertsql.=",L3_AUTO_ANSWER_NUM_17";
  $insertsql2.="','".$values['L3_AUTO_ANSWER_NUM_17'];
  $insertsql.=",L3_AUTO_ANSWER_NUM_18";
  $insertsql2.="','".$values['L3_AUTO_ANSWER_NUM_18'];
  $insertsql.=",L3_AUTO_ANSWER_NUM_19";
  $insertsql2.="','".$values['L3_AUTO_ANSWER_NUM_19'];
  $insertsql.=",L3_AUTO_ANSWER_NUM_20";
  $insertsql2.="','".$values['L3_AUTO_ANSWER_NUM_20'];

  $insertsql.=",L4_AUTO_ANSWER_NUM_1";
  $insertsql2.="','".$values['L4_AUTO_ANSWER_NUM_1'];
  $insertsql.=",L4_AUTO_ANSWER_NUM_2";
  $insertsql2.="','".$values['L4_AUTO_ANSWER_NUM_2'];
  $insertsql.=",L4_AUTO_ANSWER_NUM_3";
  $insertsql2.="','".$values['L4_AUTO_ANSWER_NUM_3'];
  $insertsql.=",L4_AUTO_ANSWER_NUM_4";
  $insertsql2.="','".$values['L4_AUTO_ANSWER_NUM_4'];
  $insertsql.=",L4_AUTO_ANSWER_NUM_5";
  $insertsql2.="','".$values['L4_AUTO_ANSWER_NUM_5'];
  $insertsql.=",L4_AUTO_ANSWER_NUM_6";
  $insertsql2.="','".$values['L4_AUTO_ANSWER_NUM_6'];
  $insertsql.=",L4_AUTO_ANSWER_NUM_7";
  $insertsql2.="','".$values['L4_AUTO_ANSWER_NUM_7'];
  $insertsql.=",L4_AUTO_ANSWER_NUM_8";
  $insertsql2.="','".$values['L4_AUTO_ANSWER_NUM_8'];
  $insertsql.=",L4_AUTO_ANSWER_NUM_9";
  $insertsql2.="','".$values['L4_AUTO_ANSWER_NUM_9'];
  $insertsql.=",L4_AUTO_ANSWER_NUM_10";
  $insertsql2.="','".$values['L4_AUTO_ANSWER_NUM_10'];
  $insertsql.=",L4_AUTO_ANSWER_NUM_11";
  $insertsql2.="','".$values['L4_AUTO_ANSWER_NUM_11'];
  $insertsql.=",L4_AUTO_ANSWER_NUM_12";
  $insertsql2.="','".$values['L4_AUTO_ANSWER_NUM_12'];
  $insertsql.=",L4_AUTO_ANSWER_NUM_13";
  $insertsql2.="','".$values['L4_AUTO_ANSWER_NUM_13'];
  $insertsql.=",L4_AUTO_ANSWER_NUM_14";
  $insertsql2.="','".$values['L4_AUTO_ANSWER_NUM_14'];
  $insertsql.=",L4_AUTO_ANSWER_NUM_15";
  $insertsql2.="','".$values['L4_AUTO_ANSWER_NUM_15'];
  $insertsql.=",L4_AUTO_ANSWER_NUM_16";
  $insertsql2.="','".$values['L4_AUTO_ANSWER_NUM_16'];
  $insertsql.=",L4_AUTO_ANSWER_NUM_17";
  $insertsql2.="','".$values['L4_AUTO_ANSWER_NUM_17'];
  $insertsql.=",L4_AUTO_ANSWER_NUM_18";
  $insertsql2.="','".$values['L4_AUTO_ANSWER_NUM_18'];
  $insertsql.=",L4_AUTO_ANSWER_NUM_19";
  $insertsql2.="','".$values['L4_AUTO_ANSWER_NUM_19'];
  $insertsql.=",L4_AUTO_ANSWER_NUM_20";
  $insertsql2.="','".$values['L4_AUTO_ANSWER_NUM_20'];

/*codec*/
  $insertsql.=",P0_PREFER_CODEC1";
  $insertsql2.="','".$values['P0_PREFER_CODEC1'];
  $insertsql.=",P0_CODEC1_DISABLE";
  $insertsql2.="','".$values['P0_CODEC1_DISABLE'];
  $insertsql.=",P0_PREFER_CODEC2";
  $insertsql2.="','".$values['P0_PREFER_CODEC2'];
  $insertsql.=",P0_CODEC2_DISABLE";
  $insertsql2.="','".$values['P0_CODEC2_DISABLE'];
  $insertsql.=",P0_PREFER_CODEC3";
  $insertsql2.="','".$values['P0_PREFER_CODEC3'];
  $insertsql.=",P0_CODEC3_DISABLE";
  $insertsql2.="','".$values['P0_CODEC3_DISABLE'];
  $insertsql.=",P0_PREFER_CODEC4";
  $insertsql2.="','".$values['P0_PREFER_CODEC4'];
  $insertsql.=",P0_CODEC4_DISABLE";
  $insertsql2.="','".$values['P0_CODEC4_DISABLE'];
  $insertsql.=",P0_PREFER_CODEC5";
  $insertsql2.="','".$values['P0_PREFER_CODEC5'];
  $insertsql.=",P0_CODEC5_DISABLE";
  $insertsql2.="','".$values['P0_CODEC5_DISABLE'];
  $insertsql.=",P0_PREFER_CODEC6";
  $insertsql2.="','".$values['P0_PREFER_CODEC6'];
  $insertsql.=",P0_CODEC6_DISABLE";
  $insertsql2.="','".$values['P0_CODEC6_DISABLE'];
  $insertsql.=",P0_PREFER_CODEC7";
  $insertsql2.="','".$values['P0_PREFER_CODEC7'];
  $insertsql.=",P0_CODEC7_DISABLE";
  $insertsql2.="','".$values['P0_CODEC7_DISABLE'];
  
  $insertsql.=",P2_PREFER_CODEC1";
  $insertsql2.="','".$values['P2_PREFER_CODEC1'];
  $insertsql.=",P2_CODEC1_DISABLE";
  $insertsql2.="','".$values['P2_CODEC1_DISABLE'];
  $insertsql.=",P2_PREFER_CODEC2";
  $insertsql2.="','".$values['P2_PREFER_CODEC2'];
  $insertsql.=",P2_CODEC2_DISABLE";
  $insertsql2.="','".$values['P2_CODEC2_DISABLE'];
  $insertsql.=",P2_PREFER_CODEC3";
  $insertsql2.="','".$values['P2_PREFER_CODEC3'];
  $insertsql.=",P2_CODEC3_DISABLE";
  $insertsql2.="','".$values['P2_CODEC3_DISABLE'];
  $insertsql.=",P2_PREFER_CODEC4";
  $insertsql2.="','".$values['P2_PREFER_CODEC4'];
  $insertsql.=",P2_CODEC4_DISABLE";
  $insertsql2.="','".$values['P2_CODEC4_DISABLE'];
  $insertsql.=",P2_PREFER_CODEC5";
  $insertsql2.="','".$values['P2_PREFER_CODEC5'];
  $insertsql.=",P2_CODEC5_DISABLE";
  $insertsql2.="','".$values['P2_CODEC5_DISABLE'];
  $insertsql.=",P2_PREFER_CODEC6";
  $insertsql2.="','".$values['P2_PREFER_CODEC6'];
  $insertsql.=",P2_CODEC6_DISABLE";
  $insertsql2.="','".$values['P2_CODEC6_DISABLE'];
  $insertsql.=",P2_PREFER_CODEC7";
  $insertsql2.="','".$values['P2_PREFER_CODEC7'];
  $insertsql.=",P2_CODEC7_DISABLE";
  $insertsql2.="','".$values['P2_CODEC7_DISABLE'];
  
  $insertsql.=",P3_PREFER_CODEC1";
  $insertsql2.="','".$values['P3_PREFER_CODEC1'];
  $insertsql.=",P3_CODEC1_DISABLE";
  $insertsql2.="','".$values['P3_CODEC1_DISABLE'];
  $insertsql.=",P3_PREFER_CODEC2";
  $insertsql2.="','".$values['P3_PREFER_CODEC2'];
  $insertsql.=",P3_CODEC2_DISABLE";
  $insertsql2.="','".$values['P3_CODEC2_DISABLE'];
  $insertsql.=",P3_PREFER_CODEC3";
  $insertsql2.="','".$values['P3_PREFER_CODEC3'];
  $insertsql.=",P3_CODEC3_DISABLE";
  $insertsql2.="','".$values['P3_CODEC3_DISABLE'];
  $insertsql.=",P3_PREFER_CODEC4";
  $insertsql2.="','".$values['P3_PREFER_CODEC4'];
  $insertsql.=",P3_CODEC4_DISABLE";
  $insertsql2.="','".$values['P3_CODEC4_DISABLE'];
  $insertsql.=",P3_PREFER_CODEC5";
  $insertsql2.="','".$values['P3_PREFER_CODEC5'];
  $insertsql.=",P3_CODEC5_DISABLE";
  $insertsql2.="','".$values['P3_CODEC5_DISABLE'];
  $insertsql.=",P3_PREFER_CODEC6";
  $insertsql2.="','".$values['P3_PREFER_CODEC6'];
  $insertsql.=",P3_CODEC6_DISABLE";
  $insertsql2.="','".$values['P3_CODEC6_DISABLE'];
  $insertsql.=",P3_PREFER_CODEC7";
  $insertsql2.="','".$values['P3_PREFER_CODEC7'];
  
  $insertsql.=",P4_PREFER_CODEC1";
  $insertsql2.="','".$values['P4_PREFER_CODEC1'];
  $insertsql.=",P4_CODEC1_DISABLE";
  $insertsql2.="','".$values['P4_CODEC1_DISABLE'];
  $insertsql.=",P4_PREFER_CODEC2";
  $insertsql2.="','".$values['P4_PREFER_CODEC2'];
  $insertsql.=",P4_CODEC2_DISABLE";
  $insertsql2.="','".$values['P4_CODEC2_DISABLE'];
  $insertsql.=",P4_PREFER_CODEC3";
  $insertsql2.="','".$values['P4_PREFER_CODEC3'];
  $insertsql.=",P4_CODEC3_DISABLE";
  $insertsql2.="','".$values['P4_CODEC3_DISABLE'];
  $insertsql.=",P4_PREFER_CODEC4";
  $insertsql2.="','".$values['P4_PREFER_CODEC4'];
  $insertsql.=",P4_CODEC4_DISABLE";
  $insertsql2.="','".$values['P4_CODEC4_DISABLE'];
  $insertsql.=",P4_PREFER_CODEC5";
  $insertsql2.="','".$values['P4_PREFER_CODEC5'];
  $insertsql.=",P4_CODEC5_DISABLE";
  $insertsql2.="','".$values['P4_CODEC5_DISABLE'];
  $insertsql.=",P4_PREFER_CODEC6";
  $insertsql2.="','".$values['P4_PREFER_CODEC6'];
  $insertsql.=",P4_CODEC6_DISABLE";
  $insertsql2.="','".$values['P4_CODEC6_DISABLE'];
  $insertsql.=",P4_PREFER_CODEC7";
  $insertsql2.="','".$values['P4_PREFER_CODEC7'];
  $insertsql.=",P4_CODEC7_DISABLE";
  $insertsql2.="','".$values['P4_CODEC7_DISABLE'];
  
  $insertsql.=",P5_PREFER_CODEC1";
  $insertsql2.="','".$values['P5_PREFER_CODEC1'];
  $insertsql.=",P5_CODEC1_DISABLE";
  $insertsql2.="','".$values['P5_CODEC1_DISABLE'];
  $insertsql.=",P5_PREFER_CODEC2";
  $insertsql2.="','".$values['P5_PREFER_CODEC2'];
  $insertsql.=",P5_CODEC2_DISABLE";
  $insertsql2.="','".$values['P5_CODEC2_DISABLE'];
  $insertsql.=",P5_PREFER_CODEC3";
  $insertsql2.="','".$values['P5_PREFER_CODEC3'];
  $insertsql.=",P5_CODEC3_DISABLE";
  $insertsql2.="','".$values['P5_CODEC3_DISABLE'];
  $insertsql.=",P5_PREFER_CODEC4";
  $insertsql2.="','".$values['P5_PREFER_CODEC4'];
  $insertsql.=",P5_CODEC4_DISABLE";
  $insertsql2.="','".$values['P5_CODEC4_DISABLE'];
  $insertsql.=",P5_PREFER_CODEC5";
  $insertsql2.="','".$values['P5_PREFER_CODEC5'];
  $insertsql.=",P5_CODEC5_DISABLE";
  $insertsql2.="','".$values['P5_CODEC5_DISABLE'];
  $insertsql.=",P5_PREFER_CODEC6";
  $insertsql2.="','".$values['P5_PREFER_CODEC6'];
  $insertsql.=",P5_CODEC6_DISABLE";
  $insertsql2.="','".$values['P5_CODEC6_DISABLE'];
  $insertsql.=",P5_PREFER_CODEC7";
  $insertsql2.="','".$values['P5_PREFER_CODEC7'];
  $insertsql.=",P5_CODEC7_DISABLE";
  $insertsql2.="','".$values['P5_CODEC7_DISABLE'];

?>
